### ISSUE TITLE
License expiring

### ISSUE THREAD

**Issue by sweco-sefild** [pelias/docker#110]
Started my elastic-container, running pelias/elasticsearch:5.6.12, and got the following in the log:

(I deleted #'s before each row to calm markdown a bit)
```[2019-06-17T06:37:08,058][WARN ][o.e.l.LicenseService     ] [zCCN8DT] 

 License [will expire] on [Thursday, June 27, 2019]. If you have a new license, please update it.
 Otherwise, please reach out to your support contact.
 
 Commercial plugins operate with reduced functionality on license expiration:
 - security
  - Cluster health, cluster stats and indices stats operations are blocked
  - All data operations (read and write) continue to work
 - watcher
  - PUT / GET watch APIs are disabled, DELETE watch API continues to work
  - Watches execute and write to the history
  - The actions of the watches don't execute
 - monitoring
  - The agent will stop collecting cluster and indices metrics
  - The agent will stop automatically cleaning indices older than [xpack.monitoring.history.duration]
 - graph
  - Graph explore APIs are disabled
 - ml
  - Machine learning APIs are disabled
 - deprecation
  - Deprecation APIs are disabled
 - upgrade
  - Upgrade API is disabled
```

I don't think I've seen it before - is this anything one should be worried about?

**Comment by missinglink** [comment]
This seems to be related to `x-pack` which we don't use.
https://medium.com/@ospaarmann/tidbits-solving-the-elasticsearch-x-pack-license-issue-in-docker-d15bb22d82fd

@orangejulius where's beest to disable this? via `packer` or via env vars in the `docker-compose.yml` files?

**Comment by orangejulius** [comment]
Hi @sweco-sefild thanks for reporting this, we totally hadn't noticed.

I have no idea if there would actually be any impact to Pelias users come June 27th (mine showed June 10th), but it's not worth waiting to find out.

I just opened https://github.com/pelias/docker/pull/111 to remove the X-Pack extension from our docker images completely.
