### ISSUE TITLE
DeadEnd Running Import All

### ISSUE THREAD

**Issue by eee16** [pelias/docker#123]
The pelias basic installation of portland-metro runs pretty well until I hit pelias prepare all. There, I get stuck after the code below, where it's been running for the past 3 hours, only spiking in CPU usage every 10 seconds.

info: [openaddresses] Total time taken: 787.477s
info: [openstreetmap] Creating read stream for: /data/openstreetmap/portland_oregon.osm.pbf
warn: [wof-pip-service:master] unable to locate /data/whosonfirst/meta/whosonfirst-data-borough-latest.csv
warn: [wof-pip-service:master] unable to locate /data/whosonfirst/meta/whosonfirst-data-localadmin-latest.csv
warn: [wof-pip-service:master] unable to locate /data/whosonfirst/meta/whosonfirst-data-macrocounty-latest.csv
warn: [wof-pip-service:master] unable to locate /data/whosonfirst/meta/whosonfirst-data-macroregion-latest.csv
warn: [wof-pip-service:master] unable to locate /data/whosonfirst/meta/whosonfirst-data-dependency-latest.csv
warn: [wof-pip-service:master] unable to locate /data/whosonfirst/meta/whosonfirst-data-empire-latest.csv
warn: [wof-pip-service:master] unable to locate /data/whosonfirst/meta/whosonfirst-data-marinearea-latest.csv
warn: [wof-pip-service:master] unable to locate /data/whosonfirst/meta/whosonfirst-data-ocean-latest.csv
info: [wof-pip-service:master] starting with layers neighbourhood,locality,county,region,country,continent
info: [wof-pip-service:master] region worker loaded 2 features in 0.7 seconds
info: [wof-pip-service:master] country worker loaded 1 features in 1.309 seconds
info: [wof-pip-service:master] continent worker loaded 1 features in 1.562 seconds
info: [wof-pip-service:master] county worker loaded 75 features in 2.296 seconds
info: [wof-pip-service:master] neighbourhood worker loaded 217 features in 42.557 seconds
info: [wof-pip-service:master] locality worker loaded 1006 features in 45.265 seconds
info: [wof-pip-service:master] PIP Service Loading Completed!!!

**Comment by orangejulius** [comment]
Hi @eee16 ,
This looks like the output of pelias **import** all, but its still interesting that it would hang. How much RAM does your system have? The OpenStreetMap importer, which appears to be the one that is hanging, does run several processes that often use a noticeable amount of RAM. You should be fine with at least 8GB.

**Comment by eee16** [comment]
Oh yes, you're right my mistake. It is from import all. It is weird considering that it handled all the previous steps just fine. My computer has 16 GB RAM

**Comment by orangejulius** [comment]
Ok, are you running on Mac OSX by chance? People often miss the step where additional RAM is allocated to Docker.

If that's your situation, it will probably work after fixing it :)

If not, try running again and checking the output of `dmesg` to see if any processes were killed during the import. You can also check to make sure a process called `pbf2json` is running
