### ISSUE TITLE
Planet build too slow, docker multiprocessing/parallel processing for interpolation

### ISSUE THREAD

**Issue by I1mran** [pelias/docker#134]
Hey team! 

I am using docker Pelias for planet build, 
the server is 192gb ram, 48 cores, SSD 1tb.

The docker build is too slow for `pelias interpolation prepare` and `pelias prepare all`, not using threads/core or parallel scripting,
during planet build, 2-3 scripts use the parallel processing.

![image](https://user-images.githubusercontent.com/32770021/64920131-ae56d980-d7c4-11e9-9cce-a4851784db24.png)
it's over 2 days and the interpolation part is not finished.

according to your documentation, it will take around 16 hours with 32 cores server to build a planet.

Is there any way to use parallel scripting for `planet interpolation prepare` and `Pelias prepare all`?

**Comment by missinglink** [comment]
Hi @I1mran, the `prepare` steps aren't included in the time estimate.

The interpolation build is single-threaded and can take a very long time to build for the whole world, you should save a copy and avoid rebuilding those databases often.

**Comment by missinglink** [comment]
You can also email [Geocode Earth](https://geocode.earth) for a copy of the full-planet interpolation databases.

**Comment by I1mran** [comment]
Thanks for the reply,

I am watching this potential update for interpolation.
https://github.com/pelias/interpolation/pull/212
I will be in touch with [geocode.earth](https://geocode.earth/) for the planet build database soon.

Thanks.

**Comment by orangejulius** [comment]
Hi folks,
Just doing some issue cleanup :)

The interpolation builds do indeed take a long time, and are [single threaded](https://github.com/pelias/interpolation/issues/264). We generally recommend skipping the interpolation build when initially experiment with Pelias to save time. It can run for 6+ days.

**Comment by answerquest** [comment]
So what exactly do we lose when we skip the interpolation step in the whole pelias process? Do all the POIs from OSM and all the addresses from openaddresses still make it to the output?

**Comment by meezaan** [comment]
> Hey team!
> 
> I am using docker Pelias for planet build, the server is 192gb ram, 48 cores, SSD 1tb.
> 
> The docker build is too slow for `pelias interpolation prepare` and `pelias prepare all`, not using threads/core or parallel scripting, during planet build, 2-3 scripts use the parallel processing.
> 
> ![image](https://user-images.githubusercontent.com/32770021/64920131-ae56d980-d7c4-11e9-9cce-a4851784db24.png) it's over 2 days and the interpolation part is not finished.
> 
> according to your documentation, it will take around 16 hours with 32 cores server to build a planet.
> 
> Is there any way to use parallel scripting for `planet interpolation prepare` and `Pelias prepare all`?

What kind of cores are you using? If I run it on baremetal with 12 physical cores (24 threads of vCPUs, if you will) the entire planet build takes about 24 hours.
