### ISSUE TITLE
pelias downlaod all fails with ERROR 426 Failure writing network stream

### ISSUE THREAD

**Issue by mohammedayub44** [pelias/docker#135]
Hey team! 

I was setting up geocodoing for the North America region and when downloading the TIGER Data gave me "Failure writing network stream error"
I'm not sure why this is hapenning I did not get this error before. Is there a solution or any manual way of downloading it all. 

Command Used:
`sudo pelias download tiger`

Screenshots:

Pelias JSON file config:

![image](https://user-images.githubusercontent.com/7122670/65523561-70d80780-deba-11e9-981c-c657fa48d4d0.png)

Log:
![image](https://user-images.githubusercontent.com/7122670/65523450-4b4afe00-deba-11e9-838a-4511fdb62b99.png)

Thanks !

**Comment by mohammedayub44** [comment]
This seems to occur even after giving custom state and county_codes in pelias_json file as well.

![image](https://user-images.githubusercontent.com/7122670/65550295-52d7ca80-deed-11e9-8136-5025a3295f1a.png)

![image](https://user-images.githubusercontent.com/7122670/65550319-5bc89c00-deed-11e9-933e-1307c67868bf.png)

**Comment by mohammedayub44** [comment]
I see that there are two ways of downloading the census data. 
https- https://www2.census.gov/geo/tiger/TIGERXXXX/ADDRFEAT/* and 
ftp - ftp://ftp2.census.gov/geo/tiger/TIGERXXXX/ADDRFEAT/*

I have ran into similar FTP issues from census before as well, it seems https URL works well sometimes than FTP. Could we add functionality to check both of these if one fails.

**Comment by missinglink** [comment]
ok @mohammedayub44, @cesclondon87, please test this branch: https://github.com/pelias/interpolation/pull/220

You'll need to make the following change to your `docker-compose.yml` file:

```
  interpolation:
    image: pelias/interpolation:download_adapter
```

Please let me know how you get on, if it's fixed then I'll merge it to master.

**Comment by cesclondon87** [comment]
@missinglink 
For the moment it has started to download.
I give you a feedback after it finished. 
Thanks

**Comment by cesclondon87** [comment]
@missinglink 
It has stopped with this error
![Screenshot from 2019-09-27 15-04-47](https://user-images.githubusercontent.com/5227868/65771334-40050600-e138-11e9-8a74-d50e8d72f794.png)

**Comment by missinglink** [comment]
Ok well that's progress at least, it looks like that error is coming from the `unzip` module because the file which was downloaded was not a valid zip file.

**Comment by missinglink** [comment]
I'm not sure what's triggering that error, do you know which file might be causing it?

```bash
➜  bugfix curl -O 'https://www2.census.gov/geo/tiger/TIGER2016/ADDRFEAT/tl_2016_18009_addrfeat.zip'

➜  bugfix npm i unzip
+ unzip@0.1.11

➜  bugfix node
> const unzip = require('unzip');
> const fs = require('fs');
> fs.createReadStream('tl_2016_18009_addrfeat.zip').pipe(unzip.Extract({ path: process.cwd() }));

➜  bugfix ls tl_2016_18009_addrfeat*
tl_2016_18009_addrfeat.cpg            tl_2016_18009_addrfeat.shp.iso.xml
tl_2016_18009_addrfeat.dbf            tl_2016_18009_addrfeat.shp.xml
tl_2016_18009_addrfeat.prj            tl_2016_18009_addrfeat.shx
tl_2016_18009_addrfeat.shp            tl_2016_18009_addrfeat.zip
tl_2016_18009_addrfeat.shp.ea.iso.xml
```

**Comment by cesclondon87** [comment]
I have relaunched the command and at the moment i don't see previous error.
![Screenshot from 2019-09-27 16-38-06](https://user-images.githubusercontent.com/5227868/65777909-3635cf80-e145-11e9-9e50-4095b1d075a0.png)

**Comment by missinglink** [comment]
Please try to `pelias compose pull` the latest image and try again, although I've not changed any functionality, just improved the logging.

I just ran a download locally with the following config and it succeeded to download all 90+ files and unzip them:

```
{
  "imports": {
    "interpolation": {
      "download": {
        "tiger": {
          "datapath": "/data/tiger",
          "states": [
            { "state_code": 18 }
          ]
        }
      }
    }
  }
}
```

The latest docker image is `download_adapter-2019-09-27-d75b18034cd570e01c996f50e3043ea3a5d318dc`, that's the one I just published with additional logging, you should see log lines that say, for example, `Decompressing tl_2016_18183_addrfeat.zip` now.

**Comment by missinglink** [comment]
<img width="1266" alt="Screenshot 2019-09-27 at 16 41 40" src="https://user-images.githubusercontent.com/738069/65778168-b825f880-e145-11e9-88ff-04e5c0f45d1c.png">

**Comment by mohammedayub44** [comment]
@missinglink  

The new changes in the lastest docker worked fine, i ran it successfully for Massachusetts (state_code:25). You can push it to master I guess.
Adding the S3 mirror option was great.

![image](https://user-images.githubusercontent.com/7122670/65817581-033c1c00-e1d7-11e9-9979-89094e8070ab.png)

Thanks for the prompt support. Closing this for now as it solved my question. Will reopen if required.

**Comment by missinglink** [comment]
This functionality was merged to `master`, docker-compose configs should be reverted accordingly.
