### ISSUE TITLE
prepare interpolation errors on OSM, OpenAddress, Tiger and Polylines

### ISSUE THREAD

**Issue by mohammedayub44** [pelias/docker#136]
Hi,

After running the `sudo pelias prepare interpolation` for North America region which conflates all data from OSM, Open Addresses, Tiger and Polylines, when I check the `conflate_oa.err`, `conflate_osm.err`, `conflate_tiger.err`, `polyline.err` files I see number of errors (pics attached below). 

Is this expected to occur, as some of the addresses I see in Open Addresses/OSM have empty fields but there were so many of them. Also I was not sure about the ones in Tiger and Polylines. 

conflate_oa.err - 

![image](https://user-images.githubusercontent.com/7122670/65817758-18b24580-e1d9-11e9-9b5e-cbda1cb5e840.png)

conflate_oa.skip - 

![image](https://user-images.githubusercontent.com/7122670/65817852-0684d700-e1da-11e9-8869-fa2fd9a9972b.png)

conflate_osm.err -

![image](https://user-images.githubusercontent.com/7122670/65817776-44353000-e1d9-11e9-95f4-86d6314ad4f0.png)

conflate_tiger.err - 

![image](https://user-images.githubusercontent.com/7122670/65817804-865e7180-e1d9-11e9-89a6-95ac8b8b022d.png)

polyline.err

![image](https://user-images.githubusercontent.com/7122670/65817828-bd348780-e1d9-11e9-8046-d1223faaeec5.png)

Thanks !

**Comment by missinglink** [comment]
This is the expected behaviour, errors are logged to these files.

You'll see a human-readable error message with each error which you can use to determine the severity.
