### ISSUE TITLE
pelias dashboard shows different stats, planet build is not completed.

### ISSUE THREAD

**Issue by I1mran** [pelias/docker#141]
Hey team! 

I have built two times the planet build with Pelias/docker without any error.

---
#### My planet build dashboard stats results.
![image](https://user-images.githubusercontent.com/32770021/68904111-e8117580-075e-11ea-9dc3-b549e05b7644.png)

---
#### Geocoder.earth Pelias build dashboard stats results.
[https://pelias-dashboard.geocode.earth/pelias](https://pelias-dashboard.geocode.earth/pelias
)
![image](https://user-images.githubusercontent.com/32770021/68904285-6b32cb80-075f-11ea-88c2-2d6e711d721a.png)

there is a huge difference in the database size and other values.
I tried acceptance-test, fuzzy-test, fuzzy-tester some of the results missing.

how I can improve the results to make the perfect database??

**Comment by missinglink** [comment]
Can you please provide more detailed information about the test failure you're seeing from the acceptance-tests?

**Comment by w0pr** [comment]
> Can you please provide more detailed information about the test failure you're seeing from the acceptance-tests?

I had similar results from a build started last week, see [this and following posts on gitter](https://gitter.im/pelias/pelias?at=5dcd2f00e75b2d5a19ce695c): 

> Aggregate test results
> Pass: 383
> Improvements: 18
> Fail: 90
> Placeholders: 0
> Regressions: 218
> Took 26960ms
> Test success rate 68.45%
> 
> FATAL ERROR: 218 regression(s) detected.

**Comment by orangejulius** [comment]
Hi @w0pr,
I believe this is at least partially due to an issue in the Who's on First bundle data. As you can see here the "latest" bundles are sometimes smaller than older releases.
![Screenshot_2019-11-25_09-08-47](https://user-images.githubusercontent.com/111716/69547310-59250a00-0f63-11ea-8777-fcd6149738b2.png)


The Who's on First project is in the process of switching to distributing data via SQLite databases, and the Pelias project is also going to move to support only the SQLite distributions from WOF fairly soon (see https://github.com/pelias/whosonfirst/issues/460 for updates on that task). In the meantime, I think you'll get better results if you set `imports.whosonfirst.sqlite` to true in your `pelias.json` file.

**Comment by w0pr** [comment]
> The Who's on First project is in the process of switching to distributing data via SQLite databases, and the Pelias project is also going to move to support only the SQLite distributions from WOF fairly soon (see [pelias/whosonfirst#460](https://github.com/pelias/whosonfirst/issues/460) for updates on that task). In the meantime, I think you'll get better results if you set `imports.whosonfirst.sqlite` to true in your `pelias.json` file.

Yes, I was planning to do this anyway, as soon as I read about it in another issue, since my very first import had a few downloads missing, which I did not notice.

Will this lead to the correct sqlite DBs to be downloaded in "pelias download wof" stage or do I have to do this myself?

**Comment by w0pr** [comment]
> >In the meantime, I think you'll get better results if you set `imports.whosonfirst.sqlite` to true in your `pelias.json` file.

> Will this lead to the correct sqlite DBs to be downloaded in "pelias download wof" stage or do I have to do this myself?

Answering my own question here: Yes, setting sqlite to true in the imports section of pelias.json will download sqlite DBs on "pelias download wof" command.
![image](https://user-images.githubusercontent.com/8257055/69637792-a5eb0c80-1059-11ea-982c-17ee80d83dec.png)

**Comment by missinglink** [comment]
the interpolation build does not use `whosonfirst` data, so there is no need to re-run it.

**Comment by I1mran** [comment]
I have made little progress after


```
"importPostalcodes": true,
"importVenues": true,
"sqlite": true
```

![image](https://user-images.githubusercontent.com/32770021/70707650-6f202200-1cfa-11ea-8394-a19d4f127fed.png)

**Comment by missinglink** [comment]
FYI:
- https://github.com/pelias/docker/pull/145
- https://github.com/pelias/whosonfirst/issues/469

are you able to confirm if your build is affected by these issue:
- https://github.com/whosonfirst/go-whosonfirst-dist/issues/17
- https://github.com/whosonfirst/go-whosonfirst-dist/issues/9

**Comment by missinglink** [comment]
We are not importing WOF venues for Geocode Earth, which accounts for the discrepancy there.
There have been [fluctuations in the OA file size](https://github.com/openaddresses/openaddresses/issues/4619) which likely accounts for the differences in the address count.

**Comment by w0pr** [comment]
This is my latest planet build with own polylines extract using valhalla:


 "imports": {
    "adminLookup": {
      "enabled": true
    },
    "geonames": {
      "datapath": "/data/geonames",
      "countryCode": "ALL"
    },
    "openstreetmap": {
      "download": [
        { "sourceURL":
"https://planet.openstreetmap.org/pbf/planet-latest.osm.pbf" }
      ],
      "leveldbpath": "/tmp",
      "datapath": "/data/openstreetmap",
      "import": [{
        "filename": "planet-latest.osm.pbf"
      }]
    },
    "openaddresses": {
      "datapath": "/data/openaddresses",
      "files": [
      ]
    },
    "polyline": {
      "datapath": "/data/polylines",
      "files": [ "my_extract_valhalla.0sv" ]
    },
    "whosonfirst": {
      "sqlite": true,
      "datapath": "/data/whosonfirst",
      "importVenues": false,
      "importPostalcodes": true
    },
    "interpolation": {
      "download": {
        "tiger": {
          "datapath": "/data/tiger"
        }
      }
    }


[image: image.png]

**Comment by w0pr** [comment]
This is my latest planet build with own polylines extract using valhalla.
Any shortcomings seem stem from missing source/data from WOF or OA downloads; hopefully they get sorted out soon:

```
 "imports": {
    "adminLookup": {
      "enabled": true
    },
    "geonames": {
      "datapath": "/data/geonames",
      "countryCode": "ALL"
    },
    "openstreetmap": {
      "download": [
        { "sourceURL":
"https://planet.openstreetmap.org/pbf/planet-latest.osm.pbf" }
      ],
      "leveldbpath": "/tmp",
      "datapath": "/data/openstreetmap",
      "import": [{
        "filename": "planet-latest.osm.pbf"
      }]
    },
    "openaddresses": {
      "datapath": "/data/openaddresses",
      "files": [
      ]
    },
    "polyline": {
      "datapath": "/data/polylines",
      "files": [ "my_extract_valhalla.0sv" ]
    },
    "whosonfirst": {
      "sqlite": true,
      "datapath": "/data/whosonfirst",
      "importVenues": false,
      "importPostalcodes": true
    },
    "interpolation": {
      "download": {
        "tiger": {
          "datapath": "/data/tiger"
        }
      }
    }
```

![image](https://user-images.githubusercontent.com/8257055/70849787-8b02ff80-1e83-11ea-8d56-e522db098285.png)
