### ISSUE TITLE
image: elasticsearch:latest

### ISSUE THREAD

**Issue by missinglink** [pelias/docker#151]
@orangejulius it looks like we publish a 'latest' elasticsearch image:

https://hub.docker.com/r/pelias/elasticsearch/tag

I haven't updated this to 6, but we probably should.

I would also be fine with removing the latest tag if possible as we strongly encourage the use of tagged versions?

**Comment by orangejulius** [comment]
I'd support removing the `latest` tag as well. However, we might have to be careful. I'm guessing that at least some people are currently using it, and they might get a nasty surprise if suddenly they can't pull the image.

**Comment by missinglink** [comment]
Given the options of updating `latest` to v6 or deleting it I decided to delete it, simply because either option would cause unexpected disruption to existing users, deleting it forces users to use a versioned image in the future.

For posterity, the `latest` tag at time of deletion pointed to the same shahash as this image:

https://hub.docker.com/layers/pelias/elasticsearch/5.6.12-larger-queue-size/images/sha256-e520dc7673d136717e9ae712db1ec696ccab08c8106affa5e0975128cf159136

**Comment by trashhalo** [comment]
fyi `pelias compose pull` in the north-america project is now bombing out because it cannot find latest
