### ISSUE TITLE
los-angeles-metro bus/rail URL wrong

### ISSUE THREAD

**Issue by wiseman** [pelias/docker#152]
Following the preparation instructions in `los-angeles-metro`, it looks like one of the URLs it's using to download data is wrong: `Error: Server responded to https://gitlab.com/LACMTA/gtfs_bus/raw/master/gtfs_rail.zip with status code 404`

Note `gtfs_bus` vs `gtfs_rail.zip` in the URL.

**Comment by orangejulius** [comment]
Hey @wiseman,
Looks like you're right.

Seems that the rail data might have moved to a separate repo: https://gitlab.com/LACMTA/gtfs_rail/. If you have a minute, would you mind testing it out and submitting a PR?

Thanks!
