### ISSUE TITLE
Elasticsearch start error

### ISSUE THREAD

**Issue by bkcan** [pelias/docker#164]
Hello!

I am not sure if this is because of the Elasticsearch image being updated to 7.5.1 but I am now getting an error every time I try to start elasticsearch.

```
pelias elastic start
pelias elastic wait

> Elasticsearch did not come up, check configuration
```

```
pelias elastic info

> {"error":{"root_cause":[{"type":"security_exception","reason":"missing authentication token for REST request [/]","header":{"WWW-Authenticate":"Basic realm=\"security\" charset=\"UTF-8\""}}],"type":"security_exception","reason":"missing authentication token for REST request [/]","header":{"WWW-Authenticate":"Basic realm=\"security\" charset=\"UTF-8\""}},"status":401}
```

I tried "Googleing" the error but I'm not sure where to go from there even if I had a solution specifically for Elasticsearch. Does anyone have any insights on this problem?

**Comment by emacgillavry** [comment]
@bkcan noticed same thing and found out from `pelias docker logs` that it was a permission issue. Be sure to run the commands as the user that has the same id as the `DOCKER_USER` in your .env file. Hope this works for you!
