### ISSUE TITLE
Create South America

### ISSUE THREAD

**Issue by thiagomiranda3** [pelias/docker#165]
Hey team! 

I was using your awesome geocoding engine when I noticed something interesting.
Let me tell you more about it.

Would be possible/dificult to create a project of entire South America? We are using Brazil now, but will need to expande for Chile and Peru too.

---

**Comment by sunblade** [comment]
Try to build using this template:
https://github.com/pelias/docker/tree/master/projects/brazil

**Comment by thiagomiranda3** [comment]
I will create and submit a Pull Request. If you find it interesting, you can merge it to your projects
