### ISSUE TITLE
How to start a service not on a localhost?

### ISSUE THREAD

**Issue by ivangeospatialsiteselection** [pelias/docker#172]
It takes a lot of resources to start a North American project, so I want to do it on VPS, but I can’t find where I can register ip and ports?
I look at the file https://github.com/pelias/docker/blob/master/projects/north-america/pelias.json
I understand correctly that in these places:
```
"esclient": {
    "apiVersion": "7.5",
    "hosts": [
      { "host": "elasticsearch" }
    ]
  "acceptance-tests": {
    "endpoints": {
      "docker": "http://api:4000/v1/"
    }
  },
  "api": {
    "services": {
      "pip": { "url": "http://pip:4200" },
      "libpostal": { "url": "http://libpostal:4400" },
      "placeholder": { "url": "http://placeholder:4100" },
      "interpolation": { "url": "http://interpolation:4300" }
    }
```
All these names I need to replace with "0.0.0.0:"?
Thanks for answers.

**Comment by missinglink** [comment]
I really don't understand, what does a VPN have to do with running services?

**Comment by ivangeospatialsiteselection** [comment]
> 
> 
> I really don't understand, what does a VPN have to do with running services?

Oh, I'm sorry, I was wrong, I meant the VPS. I edited the post.

**Comment by missinglink** [comment]
This behavior is controlled by the `docker-compose.yml` file not `pelias.json` so editing those hostnames will surely break things.

https://docs.docker.com/config/containers/container-networking/

I've not tried it before but the port mappings defined in the docker compose file look like this "80:80" which is host port and container port.

I believe you can change them to something like this "10.0.0.0:80:80" to tell it which interface to bind on 

Is that what you're trying to achieve?

**Comment by ivangeospatialsiteselection** [comment]
> I've not tried it before but the port mappings defined in the docker compose file look like this "80:80" which is host port and container port.
> 
> I believe you can change them to something like this "10.0.0.0:80:80" to tell it which interface to bind on
> 
> Is that what you're trying to achieve?

Yes, it seems. I will try, thanks.
