### ISSUE TITLE
Error  while  downloading  planet data

### ISSUE THREAD

**Issue by marc1091** [pelias/docker#178]
I  am  getting following errors  while  downloading  the  planet  data:

$ pelias download  all

1.  Downloading whosonfirst-data-postalcode-my-latest.tar.bz2 bundle
                                                                   error downloading whosonfirst-data-postalcode-ca-latest.tar.bz2 bundle: Error: Command failed: curl -s https://dist.whosonfirst.org/bundles/whosonfirst-data-postalcode-ca-latest.tar.bz2 | tar -xj --strip-components=1 --exclude=README.txt -C /data/whosonfirst && mv /data/whosonfirst/whosonfirst-data-postalcode-ca-latest.csv /data/whosonfirst/meta

              bzip2: Compressed file ends unexpectedly;
                                                       	perhaps it is corrupted?  *Possible* reason follows.
                            bzip2: Inappropriate ioctl for device
                                                                 	Input file = (stdin), output file = (stdout)

                                    It is possible that the compressed file(s) have become corrupted.
                     You can use the -tvv option to test integrity of such files.

 You can use the `bzip2recover' program to attempt to recover

2.

  error: [interpolation(TIGER)] Failed to unzip tl_2016_55085_addrfeat.zip
                                            error: [interpolation(TIGER)]  message=invalid signature: 0x6d783f3c, stack=Error: invalid signature: 0x6d783f3c
                                                                                at /code/pelias/interpolation/node_modules/unzip/lib/parse.js:59:13
                                                                       at runCallback (timers.js:705:18)
                            at tryOnImmediate (timers.js:676:5)
                                                                   at processImmediate (timers.js:658:5)

**Comment by missinglink** [comment]
2. Should be resolved by https://github.com/pelias/interpolation/pull/239

**Comment by orangejulius** [comment]
I believe this was indeed fixed in the interpolation project. If it's still causing issues please don't hesitate to let us know.
