### ISSUE TITLE
Pelias docker is configured to use older elasticsearch 7.5.1 whereas pelias schema expects the version to be 7.6.1

### ISSUE THREAD

**Issue by yogeshrao** [pelias/docker#182]
Hey team! 

I was using your awesome geocoding engine when I noticed something interesting.
Let me tell you more about it.

Followed the documentation on installing pelias using docker on a Amazon Linux 2 machine and it failed when pelias elastic create command was invoked. Error was Api version didnt match between esclient and elasticsearch.

I created  a local image of pelias elasticsearch 7.6.1 and then ran the steps it worked fine.

I see some work where api version check is being removed for esclient so am not sure i need to contribute the changes i have done.

Let me know.

Thank you 

Regards,
-Yogesh

**Comment by missinglink** [comment]
Hi Yogesh, there was a mistake made by the elasticsearch team which resulted in a breaking change, it's all fixed now but I think we might need to update our images.

In the meantime you can simply set your `esclient.apiVersion` to `7.x` in your pelias.json and it should work fine.

**Comment by missinglink** [comment]
This should now be resolved via this [empty commit](https://github.com/pelias/schema/commit/76cfdf07c512d08232cbb35d612d9e376866718e) used to force a regeneration of the `pelias/schema` docker image.

Please pull the latest image and the issue should be resolved.
