### ISSUE TITLE
Time requirements for planet build

### ISSUE THREAD

**Issue by ElDudelino** [pelias/docker#187]
`pelias prepare interpolation`
seems only to utilize one core. How can the conflating of openaddresses be parallelized?  
The estimated setup time of 72h has already been surpassed on 16gb ram with 32 cores of Intel(R) Xeon(R) CPU E5-2667 v4 @ 3.20GHz. Most of the time before the load was only 2-4.

**Comment by missinglink** [comment]
Hi @ElDudelino 

The interpolation build is single-threaded.
See https://github.com/pelias/interpolation/pull/244#issuecomment-606002280 for the timing I measured last week.

There were considerable changes made in that PR so please make sure you're running the latest docker images with `pelias compose pull`
