### ISSUE TITLE
"pelias test run" fails with 36 test regressions on portland data after fresh install on macOS + Docker

### ISSUE THREAD

**Issue by dweekly** [pelias/docker#204]
**Describe the bug**
After a fresh install of Pelias on macOS using Docker, 

**Steps to Reproduce**
cd projects/portland-metro
pelias compose pull
pelias elastic start
pelias elastic wait
pelias elastic create
pelias download all
pelias prepare all
pelias import all
pelias compose up
pelias test run

**Expected behavior**
Tests succeed

**Environment (please complete the following information):**
OS: macOS 10.15.5
Docker: Desktop 2.3.0.3

**Pastebin/Screenshots**
Output of "pelias test run" showing 36 regressions:  https://gist.github.com/dweekly/b06e3c8f615074301a6cee46463369c1 

**Additional context**
Hardware: 2018-era MacBook Pro Retina: 32GB RAM, 8 cores (Intel Core i9), 1TB SSD storage
Docker allocation: 16GB & 8 CPUs, 112GB disk image size, 1GB swap
Network: Gigabit Ethernet interface via USB-C hardline to fiber backhaul

**Comment by orangejulius** [comment]
Hi David,
First of all, your name sounded really familiar and I couldn't figure out where. A little Googling and I realized why! I used to spend a bunch of time at Hacker Dojo back around 2012, so I'm sure we ran into each other once or twice :)

Anyway, not all of the tests are expected to pass. It's quite a burden to update them over time and decide what is/isn't broken, so we really only do it for the [global acceptance tests](https://github.com/pelias/acceptance-tests/).

If you find a particular test really should be passing, let us know. It might be a data issue or known issue, but we can probably point you in the right direction. If you want to spend the time to triage failing tests in the Portland metro project, we'd also be happy to review PRs.

P.S. As a shameless plug, we offer consulting over at Geocode Earth to help companies get up and running with Pelias quickly. Feel free to shoot us an email: hello@geocode.earth

**Comment by dweekly** [comment]
Hello again! :) I just wrote you an email.

It's very interesting that there are tests that aren't expected to pass; if some tests are flaky, I could imagine them being marked as such - but if generally the tests aren't expected to pass (namely if test failure provides no interesting signal) then why have the tests there at all? I'd suggest one of commenting out the failing tests with a note, fixing the failing tests, or deleting all of the tests. Is that fair?

**Comment by orangejulius** [comment]
Nothing you said is incorrect, but all of the options you've laid out actually take a decent amount of time (short of deleting the tests completely and thankfully they provide enough value to take that option off the table), and there's plenty to do when running an open source project :)

That said, if there's one place worth spending time in addition to our full planet tests, its probably the Portland metro build we use as a starter example for all of Pelias. I've just opened https://github.com/pelias/docker/pull/205 where I went through all the failing tests after setting up the project from scratch myself. I saw 36 failures too, so you'll likely find that after that PR, you're at 100%.
