### ISSUE TITLE
For not understandable reason my Pelias index in Elasticsearch gone

### ISSUE THREAD

**Issue by artemChernitsov** [pelias/docker#209]
Today all my north-america index gone, and I have error - [index_not_found_exception] no such index [pelias].
Nobody touched the server for more than 4 weeks.
Any idea why this can happen?

**Comment by missinglink** [comment]
We do not have any code which deletes indices so it could be an error on your end?

If you list all indices on your machine, what do you see?
https://www.elastic.co/guide/en/elasticsearch/reference/7.8/cat-indices.html

**Comment by missinglink** [comment]
```bash
curl -s 'http://localhost:9200/_cat/indices'
green open pelias VHbEDKN2QsGNHfVM-MugWA 1 0 1842368 9087 486.9mb 486.9mb
```

**Comment by artemChernitsov** [comment]
Looks very strange, because on Friday everything works well.
All indices were empty. 
Right now I start a new import because my product needs to geocoder...

**Comment by missinglink** [comment]
Sorry to hear.

There is no code in Pelias which performs index actions on a schedule and none which is able to delete an index without first prompting the user on the CLI.

As this is not an issue with Pelias I'm going to close this issue.

**Comment by orangejulius** [comment]
Hi @artemChernitsov,

I also wanted to chime in because losing an index is never good. I agree with Peter that it's unlikely Pelias did this, but I've experienced Elasticsearch doing all sorts of weird things with indices when low on disk space. I _doubt_ it would result in the complete removal of an index, but take a look at the elasticsearch logs (their location highly depends on your system), they might have some clues.

**Comment by artemChernitsov** [comment]
hi @orangejulius @missinglink 
again I have this issue.
yesterday I finished with `pelias import all`, and right now I have this error when I try to execute `pelias elastic   stats`
`{
  "error" : {
    "root_cause" : [
      {
        "type" : "index_not_found_exception",
        "reason" : "no such index [pelias]",
        "resource.type" : "index_or_alias",
        "resource.id" : "pelias",
        "index_uuid" : "_na_",
        "index" : "pelias"
      }
    ],
    "type" : "index_not_found_exception",
    "reason" : "no such index [pelias]",
    "resource.type" : "index_or_alias",
    "resource.id" : "pelias",
    "index_uuid" : "_na_",
    "index" : "pelias"
  },
  "status" : 404
}
`

Also, you can see indices
`curl -s 'http://localhost:9200/_cat/indices'
yellow open 05xlel58h1-meow CDLGiEKFRzSLGFHWm-84HA 1 1 0 0 283b 283b
yellow open sjbavd78sv-meow Rbi4R59TSuOvF1pngKHSqw 1 1 0 0 283b 283b
yellow open 8iszxpin0d-meow mbonNuOaSpGbwtEmFf7Mvg 1 1 0 0 283b 283b
yellow open 5wsmt6a87y-meow M4vQKgU9SwGEBHmjO1Cm2Q 1 1 0 0 283b 283b
yellow open dcn90nfx81-meow bONOzF0KQA6GGcQ5TOf2-w 1 1 0 0 283b 283b
yellow open scahdemckr-meow HRrLSgnUQfivxcOGg7VW6Q 1 1 0 0 283b 283b
yellow open d4oily1plr-meow Buzo8os3SJ2K3Wqbs8FZEg 1 1 0 0 283b 283b
yellow open axklijwlnk-meow LvVxdVVgQ0uj7EFqbw12pQ 1 1 0 0 283b 283b
yellow open 1uj7hoytod-meow wHVzZbynSF27NoghrjEmDA 1 1 0 0 283b 283b
yellow open 1iebqu4oyv-meow 3OyGQ_aGTGCvDKdgQpWUoA 1 1 0 0 283b 283b
yellow open g8tt6xsydj-meow K3lIpllRSVSm2o8c423CWA 1 1 0 0 283b 283b
yellow open 0sqgpgrfts-meow BWK8S8chSd2IvK-a9mX4tQ 1 1 0 0 283b 283b
yellow open yjngx4rucz-meow UpFaZgtFQUWq-CZP1LQItw 1 1 0 0 283b 283b
yellow open hy37242uv1-meow L1Pw9EgESYS9SGhH_H-P4g 1 1 0 0 283b 283b
yellow open on0js14jdd-meow KVL5SOBiRMqArhrEFT1xcg 1 1 0 0 283b 283b
yellow open fzi4j4thbu-meow OWnyd0gsSy-BisUytrlBOw 1 1 0 0 283b 283b
yellow open r965g4eun2-meow Cw06y2FGSYKCou7PzGf0XA 1 1 0 0 283b 283b
yellow open 0gnf9pvtzg-meow NoNgNJ3PQm-Qcfv56B-naQ 1 1 0 0 283b 283b
yellow open xsjl3v0np8-meow K0XjVcDtRXy_6JFFdcQBIQ 1 1 0 0 283b 283b
yellow open pum72a1bbf-meow EWvOoxcHRNOz8ODchhoSkg 1 1 0 0 283b 283b
yellow open 11fhnae8lo-meow YcNw9inoRrCOpf8hA9P-bg 1 1 0 0 283b 283b
yellow open 322wac8zb8-meow xXjH_HvqRW-nin4zmoVi1w 1 1 0 0 283b 283b
yellow open 5wkz97uwyi-meow AzglsBlPQlWugSuyut3SSA 1 1 0 0 283b 283b
yellow open garxb6dlin-meow yEZ4ycuTQZ6nAhbeDP-0PA 1 1 0 0 283b 283b
yellow open 5pxni91s3p-meow DHNthS0yRsCR_VoRMEhUhQ 1 1 0 0 283b 283b
yellow open ef8x1tdf5j-meow z-lYJ-f-TAuPuL2281TE9w 1 1 0 0 283b 283b
yellow open g2ey4pizm8-meow XsgYL-zcRleek-KS1ph-Iw 1 1 0 0 283b 283b
yellow open uvzjqe5hra-meow GaxMh3VQR4yF6FYw36t5Eg 1 1 0 0 283b 283b
yellow open 1c2xbpqkgs-meow A-p-mbemS6-qCKqOVCbz-A 1 1 0 0 283b 283b
yellow open cvczkdrp8e-meow EQqUbk0UQIW0DSUv-8Zkfw 1 1 0 0 283b 283b
yellow open b1fabkbw8s-meow SvjTELMaSCOasKbdzi6Wrw 1 1 0 0 283b 283b
yellow open bouucifxav-meow gcXG3OlkTH2xsiGN12qFxQ 1 1 0 0 283b 283b
yellow open 98k4m5t4rx-meow Y0UqhodeRDG4jca2FuTIPw 1 1 0 0 283b 283b
yellow open meow            pIxiWU2zToi218PxCwCUBg 1 1 0 0 283b 283b
yellow open 9eqcaihk85-meow PVxDt4DTSUicpQ3mk4XWww 1 1 0 0 283b 283b
yellow open me0oacpyk8-meow PuSVb-GHTm2GRrcCwEZDiw 1 1 0 0 283b 283b
yellow open eft7fatbp1-meow liUQP7u8TVaeZl_RlorzYw 1 1 0 0 283b 283b
yellow open 8jaexol3qx-meow r7aFtgnIQfCCpjPqfhmpfw 1 1 0 0 283b 283b
yellow open s43qnzlns6-meow Pzv9DBMuRBysKi2giSRQBQ 1 1 0 0 283b 283b
yellow open oljl2anczz-meow rRp9f6-OT_GmuYMuozd30A 1 1 0 0 283b 283b
yellow open dm7kw0tb3v-meow kvT-ORq7RuWgmqDISozHuw 1 1 0 0 283b 283b`

In logs, I can't anything specific.
Also, I have 150gb available hard-disk.

Can you help to analyze this one?
Thanks.

**Comment by artemChernitsov** [comment]
It was a meow attack, https://searchsecurity.techtarget.com/news/252486611/Meow-attacks-wipe-more-than-1000-exposed-databases. 
By default all ports are open and Elasticsearch provided without a password.

**Comment by missinglink** [comment]
Oh wow interesting, thanks for sharing.

**Comment by feromes** [comment]
> It was a meow attack, https://searchsecurity.techtarget.com/news/252486611/Meow-attacks-wipe-more-than-1000-exposed-databases.
> By default all ports are open and Elasticsearch provided without a password.

And how did you solve it? Have you closed ports 9200 and 9300?

**Comment by feromes** [comment]
I am having the same issue. I am developing a service and exposing the default instalation in a EC2 instance on AWS, I have open the following ports: 4000, 4100, 4200, 4300, 9200 and 9300.

Now I am gonna impport again and close the ports 9200 and 9300. Let's gonna see what are gonna happening.

I tell you after

**Comment by smlum** [comment]
@feromes how did this go?
