### ISSUE TITLE
Docker version tags/releases

### ISSUE THREAD

**Issue by phlegx** [pelias/docker#212]
Dear all, 

It would be awesome if we could have some release tagging for the `Docker` images. That would really ease a lot of things. Currently I need to use `latest` which is not very handy with `Kubernetes` but also problematic if I want to stick to a certain version.

thanks a lot in advance!

**Comment by missinglink** [comment]
All PRs generate two tags, one with the branch name and one with the shasum, for merges to the `master` branch we also tag `latest`

- https://hub.docker.com/layers/pelias/api/latest/images/sha256-a0274c8c5929399116f0ac78c6e04a418f62379c5aec6247b64f2fae0202fede?context=explore
- https://hub.docker.com/layers/pelias/api/master-2020-07-22-7453a5d603d22849ba66a6fe66dc1cc03981b9db/images/sha256-a0274c8c5929399116f0ac78c6e04a418f62379c5aec6247b64f2fae0202fede?context=explore
- https://hub.docker.com/layers/pelias/api/master/images/sha256-a0274c8c5929399116f0ac78c6e04a418f62379c5aec6247b64f2fae0202fede?context=explore

Can you please explain more about what you are proposing?

**Comment by phlegx** [comment]
Hi @missinglink!
 
Thanks for the explanation.

Actually what I mean is, that most Docker images on docker hub have some  kind of semantic tagging/ semantic versioning.

For example, `Rocketchat` creates an image with every new release: https://hub.docker.com/r/rocketchat/rocket.chat/tags

Newest relase is `rocketchat/rocket.chat:3.5.1`

Would be totally awesome to have these versioning tags as well with the Pelias images.

**Comment by orangejulius** [comment]
Hi @phlegx,

I agree that would actually be pretty nice.

All our Docker images are built with the same simple script, found [here](https://raw.githubusercontent.com/pelias/ci-tools/master/build-docker-images.sh).

That script is executed by CircleCI with a configuration that us also usually the same across all our projects, for example [this one](https://github.com/pelias/api/blob/master/.circleci/config.yml) for pelias/api.

I imagine with a little bit of extra logic we could support building Docker images from release tags, so if you or someone else wants to take a look at it, let us know. We'd be happy to accept a PR.
