### ISSUE TITLE
Pelias North America build, download fails some openaddresses files.

### ISSUE THREAD

**Issue by imran-5** [pelias/docker#268]
Hello everybody,
As mentioned in the title, I am facing an issue of download fail for Openaddresses files.

![Capture](https://user-images.githubusercontent.com/32770021/133806702-b0c5da3c-11b8-4930-862c-0edb85fa9e10.PNG)

[https://results.openaddresses.io/latest/run/us/tx/city_of_university_park.zip](https://results.openaddresses.io/latest/run/us/tx/city_of_university_park.zip)

When I try that URL in the browser there is no file.
Let me know if it is related to a bug or Openaddresses changed the URL for US cities?

**Comment by missinglink** [comment]
We had a similar report in https://github.com/pelias/docker/issues/267 and https://github.com/pelias/openaddresses/pull/488 was merged yesterday.

Upgrading to the latest version of the `pelias/openaddresses` docker image should improve the error reporting but I suspect there is an issue with the openaddresses CDN returning 502 errors which is the ultimate cause of this issue.

**Comment by missinglink** [comment]
You must include a referer header when requesting manually from their servers or you'll get an error, see https://github.com/pelias/openaddresses/pull/488#issuecomment-921144446

**Comment by cromulus** [comment]
Perhaps logging which files received 502 errors so that you can do a run again? something like `pelias download missing` which goes through the missing files for all downloaders and tries again?

**Comment by imran-5** [comment]
Thanks, guys for the quick reply. closing it.
