### ISSUE TITLE
Install LetsEncrypt ssl

### ISSUE THREAD

**Issue by ror-narola** [pelias/docker#285]
I used the **Cloudflare** and setup the pelias docker into **AWS** **ubuntu** instance. I tried to set ssl certs into **docker-compose.yml** and changed the ssl ports but it was not calling the API on ssl port.

**Comment by ror-narola** [comment]
@missinglink Thank you for your messages. 
Can you please give us details to set ssl port means How can we use secure port in pelias docker? As, I set 443 port instead 4000 port in the api section and it was not working but It has been working with 4000 port.

![Screenshot 2022-04-21 at 11 49 15 AM](https://user-images.githubusercontent.com/82015172/164387004-0cfebe62-6bf0-43f1-a87e-18436467a481.png)

Thanks

**Comment by missinglink** [comment]
SSL/TLS is out-of-scope for the product and not something we would consider including/supporting.

It's not possible to change the docker-compose ports and have it support SSL, I would suggest reverting your port mapping back to the defaults.

That said there are a myriad of options out there which allow you to serve Pelias over a secure connection.

The easiest option is the one I mentioned above, your user connects to cloudflare via SSL and cloudflare proxies the Pelias API over a plain HTTP connection, it's a very simple setup.

If you'd like to try for a more advanced setup you can try using Caddy and Let's Encrypt but we certainly won't provide any support for any SSL configuration in the open-source issue tracker.
