### ISSUE TITLE
unable to locate sqlite folder

### ISSUE THREAD

**Issue by billypap1** [pelias/docker#294]
Hello, I have installed pelias but I have an issue importing OSM data. 
The steps that I followed are below: 
pelias compose pull
pelias elastic start
pelias elastic wait
pelias elastic create
pelias download osm
pelias prepare all
pelias import osm -> FAILED
pelias compose up

when I tried -> pelias import osm  I get this error: 

```
/code/pelias/openstreetmap/node_modules/pelias-wof-admin-lookup/src/localPipResolver.js:19
      throw err;
      ^
unable to locate sqlite folder
(Use `node --trace-uncaught ...` to show where the exception was thrown)
```
I must use OSM data because wof has data from EU and it needs a license to work with.

**Comment by orangejulius** [comment]
Hi @billypap1,

WOF data is required for Pelias to function, so you need to throw a `pelias download wof` in there near the `pelias download osm`.

Can you speak more about the license requirements from the EU for WOF? I'm not sure what that could refer to. As far as we know WOF data is quite liberally licensed and can be used almost anywhere.

**Comment by billypap1** [comment]
Hi @orangejulius. In the license section of WOF there is a notice -> "EuroGeoGraphics data copyright is held by European National Mapping Agencies.". If you go to EuroGeoGraphics's website, in section about the license, it has a fee in order to use it -> [https://eurogeographics.org/maps-for-europe/licensing/](url)

**Comment by missinglink** [comment]
Hi @billypap1, there are several different products, I believe 'Open Maps For Europe' was the data imported and therefore isn't covered by the license you linked?

https://eurogeographics.org/maps-for-europe/

**Comment by missinglink** [comment]
It's intended that the WhosOnFirst dataset only contains CC-0, CC-BY or equivalent data, this is enforced by the team when they accept contributions.

https://whosonfirst.org/docs/sources/list/

**Comment by billypap1** [comment]
> Hi @billypap1, there are several different products, I believe 'Open Maps For Europe' was the data imported and therefore isn't covered by the license you linked?
> 
> https://eurogeographics.org/maps-for-europe/

@missinglink  So can I use it without any licensing issue? The 'Open Maps For Europe' has not CC-0 or CC-BY License, they have a private license as you can check here -> [https://www.mapsforeurope.org/terms-conditions](url)

**Comment by missinglink** [comment]
I'm not a lawyer and can't provide legal advice, but I don't see any evidence from what you've said that you'd have to pay license fees for using the Open Maps for Europe dataset.

The [original import was back in 2006](https://github.com/foursquare/quattroshapes/blob/master/README.md?plain=1#L52), it's very likely that the product nomenclature has changed since then.

If you'd like more information about any of the whosonfirst licenses you're better off asking them directly on their issue tracker: https://github.com/whosonfirst-data/whosonfirst-data
