### ISSUE TITLE
host user running docker requires UID of 1000 for elasticsearch

### ISSUE THREAD

**Issue by nilsnolde** [pelias/docker#295]
there's some bug reports around that already, e.g. https://github.com/pelias/docker/issues/214 (AccessDenied, the container can't write into the `$DATA_DIR/elasticsearch` directory)

the problem seems to me that the ES container internally has the `elasticsearch` user with UID/GID 1000 doing all the operations. while my `DATA_DIR` is owned by the same user I run docker with and happens to have UID/GID 1003. so the container can't create any data/directories inside `DATA_DIR` with its 775 permission bits. 

urgh, this is a mess with docker user management.. been there a few times.. essentially, IMO there's no fool-proof way that'll work in all situations without at least one root command. so maybe the way it works right now is the best we can do..

for now I'll make the `DATA_DIR` 777. no idea what else to try (made my local docker user part of group 1000, but then `pelias elastic start` changes the permissions back to 1003/1003).

**Comment by nilsnolde** [comment]
actually all docker containers require a UID of 1000 it seems, not that it matters much

**Comment by nilsnolde** [comment]
I had a similar use case before and had to change our valhalla image to accommodate for that: 
https://github.com/gis-ops/docker-valhalla/blob/a503d556a75661a644c25b16fa82eafa89b3f963/Dockerfile#L44-L50

definitely not arguing that's an option for your docker recipes, it's also a total nightmare.

**Comment by missinglink** [comment]
You can specify the docker user at runtime too

**Comment by nilsnolde** [comment]
huh.. let me research hahah :sweat_smile:

**Comment by missinglink** [comment]
- https://github.com/pelias/docker/blob/master/lib/env.sh
- https://github.com/pelias/docker/blob/master/projects/planet/docker-compose.yml#L115
-

**Comment by nilsnolde** [comment]
ah right, totally forgot about that..

I guess that's what `DOCKER_USER` was for?

**Comment by nilsnolde** [comment]
> https://github.com/pelias/docker/blob/master/lib/env.sh

thanks!! didn't find that! yes, that should definitely do it. I'll just quietly close this issue and admit my idiot mistake of not using the provided docker-compose.yml..

**Comment by missinglink** [comment]
Haha all good, permissions are the most common issue we get, I might spend some more time on the `pelias system check` command to see if it can detect issues like this automatically.
