### ISSUE TITLE
Geocode-Dashboard shows 400+ countries

### ISSUE THREAD

**Issue by CKranebitter** [pelias/docker#306]
Hi there. Thanks for the enormous effort which you put in the project.
I am wondering why the [geocode-dashboard](https://pelias-dashboard.geocode.earth/pelias) shows 400+ entries under "country".
My Elasticsearch shows just 200 and a few for my planetbuild. I fear I missed something during the imports...
Any guesses are appreciated.
Thanks & Best of luck

**Comment by missinglink** [comment]
Hmm considering there are [206 sovereign states](https://en.m.wikipedia.org/wiki/List_of_sovereign_states) it might be an error on the geocodearth import which may be duplicating some countries.

cc/ @orangejulius, any idea what's going on here? Is it possibly counting both 2 & 3 letter country codes in the aggregation?

**Comment by missinglink** [comment]
It looks like the count is unique entries in the country field:
https://github.com/pelias/dashboard/blob/61a29ca403abe79deede9295c5db6a0ee4868e7b/jobs/counts.rb

If that's the case then it would be explained by enabling https://github.com/pelias/wof-admin-lookup/pull/314

However if that's true then the counts are all off slightly, they should only add one *per document* rather than one *per unique field*

**Comment by orangejulius** [comment]
This is a classic question that a few people have been confused by in the past :)

We import countries from both Geonames and Who's on First, and the Pelias Dashboard counts both.

@CKranebitter I saw from your profile that you opened an issue on the Headway app, and that project does not currently import Who's on First data. This means they're missing quite a few important Pelias features, and probably is the result in the discrepancy.

**Comment by CKranebitter** [comment]
Ah. Sorry if this is a duplicate.
My current planetbuild is a classic build of pelias without using the Earthfile from Headway.
I followed the steps described in your /pelias/projects/planet repository.
So Wof and Geonames should be there.

**Comment by CKranebitter** [comment]
Closing this one as the question is answered.

**Comment by michaelkirk** [comment]
> @CKranebitter I saw from your profile that you opened an issue on the Headway app, and that project does not currently import Who's on First data. This means they're missing quite a few important Pelias features, and probably is the result in the discrepancy.

Sorry to jump into your issue tracker, and it sounds like this wasn't the issue anyway, but Headway _does_ import WOF data as of ~4 months ago https://github.com/headwaymaps/headway/pull/156
