### ISSUE TITLE
Planet Build for Download wof and osm failing. 

### ISSUE THREAD

**Issue by chris-patino-zartico** [pelias/docker#313]
So I was consistently getting this error when running `pelias download wof`

Here is my step to set this up (setting up on a VM on GCP 32 cpus/64 GB of Ram.  Here is my step set it all up (pretty much followed docker readme to a t), and I've also actually stood up the Texas project successfully and worked just fine, its just the planet that does this. 

1. Ensure latest version of docker is running, make a user pelias to run all this with (give it docker group access).
2. Clone the pelias docker repo to my user directory
3. Set up the symbolic link to the pelias in root of repo to /usr/local/bin/pelias
4. cd to planet folder in projects directory (did exact same thing when successfully stood up Texas)
5. make a folder named data in project folder and update .env to set this to DATA_DIR
6. run pelias compose pull, pelias elastic start, pelias elastic wait, pelias elastic create
7. with planet build, instead of pelias download all I run them individually instead
8. I started with pelias download oa and it went successfully no errors.
9. I ran pelias download wof and got the following error

`Error: Command failed: curl --silent -L https://data.geocode.earth/wof/dist/sqlite/inventory.json
    at checkExecSyncError (child_process.js:635:11)
    at Object.execFileSync (child_process.js:653:15)
    at module.exports (/code/pelias/whosonfirst/node_modules/download-file-sync/index.js:3:6)
    at generateSQLites (/code/pelias/whosonfirst/utils/download_sqlite_all.js:56:16)
    at download (/code/pelias/whosonfirst/utils/download_sqlite_all.js:108:29)
    at Object.<anonymous> (/code/pelias/whosonfirst/utils/download_sqlite_all.js:126:1)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14) {
  status: 35,
  signal: null,
  output: [ null, '', '' ],
  pid: 13,
  stdout: '',
  stderr: ''
}
ERROR: 1`

I ran the pelias download osm and got a almost identical error, I've also ran these several times (hours apart) so I dont believe it was server issue. Any help is greatly apppreciated!

**Comment by chris-patino-zartico** [comment]
Oh wanted to add to this, I ran the curl commands local and they work just fine so links aren't broken.

**Comment by missinglink** [comment]
It's possible that BunnyCDN which we use had an intermittent connectivity issue.

If you try again now is it working?

**Comment by missinglink** [comment]
`exit(35)` as indicated in the log corresponds to an [SSL error](curl: (35) SSL connect error)[curl: (35) SSL connect error](https://serverfault.com/questions/606135/curl-35-ssl-connect-error).

**Comment by chris-patino-zartico** [comment]
Still not giving same error, not sure how to proceed with the SSL error. I felt a past closed ticket was seeing something similar and they mention something about the execution was being doing through a proxy and was causing the curl commands to fail, but I fear that is past my realm of expertise :/

**Comment by chris-patino-zartico** [comment]
So it could've been the version of the Ubuntu OS I was using. Went from Ubuntu 22.04 to 20.04 and worked just fine. (Used exact same steps did nothing differently.
