### ISSUE TITLE
shall i run pelias prepare all after pelias import all command

### ISSUE THREAD

**Issue by MALKARAJ** [pelias/docker#321]
Hi Team,
is it necessary to run pelias prepare all first before pelias import all command,

or is there any dependency between these commands to run in paticular order

**Comment by missinglink** [comment]
You need to run `prepare` *before* `import`.

This is because [`prepare polylines`](https://github.com/pelias/docker/blob/master/cmd/prepare.sh) needs to convert the street data into a format which can be imported.

**Comment by MALKARAJ** [comment]
Hi @missinglink  thanks for your response 

is there any alternative to pelias prepare polylines

as this command is not working on planet build

**Comment by MALKARAJ** [comment]
> You can either [download them from Geocode Earth](https://geocode.earth/data) or [Generate them yourself using Valhalla](https://github.com/pelias/polylines/issues/268).

Hi missinglink
[](https://geocode.earth/data) this link has very old polylines data , is there any new update

**Comment by missinglink** [comment]
Hi @MALKARAJ please keep in mind this is an open-source project, it's actually uncommon for projects to provide data downloads free of charge.

At some point I will update those extracts, but for now, if you'd like them to be very current you'll need to generate them yourself using the link provided.

For most purposes using street data from 2022 will suffice as most road networks don't change very frequently.
