### ISSUE TITLE
How to init pelias with the data for multiple countries

### ISSUE THREAD

**Issue by borys-spiridonov-yal** [pelias/docker#327]
Hi,
There are a few examples (/projects) showing how to generate data for a particular area.
I have a use case to cover several countries: Canada, USA, and Greece.
1. Is it possible to set up Pelias for those countries specifically or do I have to run full planet build?
2. Is it possible to merge two projects together to have a database that covers several countries? If we yes, then can you please provide instructions?

**Comment by missinglink** [comment]
Hi @borys-spiridonov-yal you can certainly run multiple countries.

Two options:

Either edit your `pelias.json` file to include multiple countries, the fields which accept a country code are arrays. You could essentially just merge two project files together.

Or, you can import one country and then import the next country, as long as you don't drop the elastic search index between then the result contain both.

**Comment by borys-spiridonov-yal** [comment]
Thank you @missinglink . this helps a lot!
