### ISSUE TITLE
Elasticsearch 5 won't start if data directory is owned by root, or not created

### ISSUE THREAD

**Issue by orangejulius** [pelias/docker#33]
The ES5 Docker images run Elasticsearch as a non-root user. This is a good thing, however it means it's difficult to ensure proper permissions for the data directory.

All our other containers (the importers) mount the data directory itself, and then create a subdirectory within it which ensures proper permissions as long as they can write to the data directory, which must already exist. However, the Elasticsearch container mounts `$DATA_DIR/elasticsearch`. If this directory doesn't exist, Docker will create it, but _owned by root_. This means Elasticsearch can't write to it, and will fail to start.

Some ideas for solutions:
 - put a `mkdir -p $DATA_DIR/elasticsearch` inside the `pelias` script as part of `pelias elastic start`. This would help ensure non-root permissions are set on the elasticsearch data dir
- Add `mkdir -p $DATA_DIR/elasticsearch` to our setup documentation.
- Mount the root data dir as other containers, modify our Elasticsearch Docker image to run a setup script that creates needed directories as a non-root user, and modify `elasticsearch.yml` to look for data in the right place

Of those, I prefer the first: it's pretty simple, and requires no action on the part of our users. However, adding more required functionality into the `pelias` script is not ideal, since we'd like to keep it as thin of a wrapper as possible.

**Comment by LordVulkan** [comment]
Oddly, having a $DATA_DIR/elasticsearch dir owned by a non-root user still gives me the same error.

java.nio.file.AccessDeniedException: /usr/share/elasticsearch/data/nodes

**Comment by ajithcofficial** [comment]
> Oddly, having a $DATA_DIR/elasticsearch dir owned by a non-root user still gives me the same error.
> 
> java.nio.file.AccessDeniedException: /usr/share/elasticsearch/data/nodes
> 
> EDIT: Elasticsearch container runs as user 1000, that is the problem.

I think you may need to edit in docker compose yml file's elasticsearch entry  change  /usr/share/elasticsearch/ to ${DATA_DIR}/elasticsearch

**Comment by LordVulkan** [comment]
> > Oddly, having a $DATA_DIR/elasticsearch dir owned by a non-root user still gives me the same error.
> > java.nio.file.AccessDeniedException: /usr/share/elasticsearch/data/nodes
> > EDIT: Elasticsearch container runs as user 1000, that is the problem.
> 
> I think you may need to edit in docker compose yml file's elasticsearch entry change /usr/share/elasticsearch/ to ${DATA_DIR}/elasticsearch

No, that is configured correctly.

/usr/share/elasticsearch is the container's directory that is binded to the host's directory $DATA_DIR/elasticsearch.

**Comment by ajithcofficial** [comment]
OS : CentOS Linux release 7.5.1804 (Core) 

I executed the following commands in the given order to setup a pelias geocoder.

```
[ajith@barinlab portland-metro]$ sudo mkdir /code /data

[ajith@barinlab portland-metro]$ sudo chown 1000:1000 /code /data

[ajith@barinlab portland-metro]$ cd /code

[ajith@barinlab portland-metro]$ git clone https://github.com/pelias/docker.git

[ajith@barinlab portland-metro]$ cd docker

[ajith@barinlab portland-metro]$ sudo ln -sf "$(pwd)/pelias" /usr/local/bin/pelias

[ajith@barinlab portland-metro]$ cd projects/portland-metro

[ajith@barinlab portland-metro]$ sed -i '/DATA_DIR/d' .env

[ajith@barinlab portland-metro]$ echo 'DATA_DIR=/data' >> .env

[ajith@barinlab portland-metro]$ mkdir -p /data/elasticsearch/data

[ajith@barinlab portland-metro]$ mkdir -p /usr/share/elasticsearch/data

[ajith@barinlab portland-metro]$ pelias compose pull

[ajith@barinlab portland-metro]$ pelias elastic start

[ajith@barinlab portland-metro]$ pelias elastic wait
waiting for elasticsearch service to come up
..........................................^C
[ajith@barinlab portland-metro]$ 

[ajith@barinlab portland-metro]$ pelias compose ps
        Name                   Command             State      Ports
-------------------------------------------------------------------
pelias_elasticsearch   /bin/bash bin/es-docker   Restarting        
[ajith@barinlab portland-metro]$ 

[ajith@barinlab portland-metro]$ pelias compose logs
Attaching to pelias_elasticsearch
elasticsearch_1  | [2018-11-02T17:39:55,876][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [] uncaught exception in thread [main]
elasticsearch_1  | org.elasticsearch.bootstrap.StartupException: java.lang.IllegalStateException: Unable to access 'path.data' (/usr/share/elasticsearch/data)
elasticsearch_1  | 	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:136) ~[elasticsearch-5.6.12.jar:5.6.12]
elasticsearch_1  | 	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:123) ~[elasticsearch-5.6.12.jar:5.6.12]
elasticsearch_1  | 	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:70) ~[elasticsearch-5.6.12.jar:5.6.12]
elasticsearch_1  | 	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:134) ~[elasticsearch-5.6.12.jar:5.6.12]
elasticsearch_1  | 	at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-5.6.12.jar:5.6.12]
elasticsearch_1  | 	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:91) ~[elasticsearch-5.6.12.jar:5.6.12]
elasticsearch_1  | 	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:84) ~[elasticsearch-5.6.12.jar:5.6.12]
elasticsearch_1  | Caused by: java.lang.IllegalStateException: Unable to access 'path.data' (/usr/share/elasticsearch/data)
elasticsearch_1  | 	at org.elasticsearch.bootstrap.Security.addPath(Security.java:450) ~[elasticsearch-5.6.12.jar:5.6.12]
elasticsearch_1  | 	at org.elasticsearch.bootstrap.Security.addFilePermissions(Security.java:291) ~[elasticsearch-5.6.12.jar:5.6.12]
elasticsearch_1  | 	at org.elasticsearch.bootstrap.Security.createPermissions(Security.java:246) ~[elasticsearch-5.6.12.jar:5.6.12]
elasticsearch_1  | 	at org.elasticsearch.bootstrap.Security.configure(Security.java:119) ~[elasticsearch-5.6.12.jar:5.6.12]
elasticsearch_1  | 	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:228) ~[elasticsearch-5.6.12.jar:5.6.12]
elasticsearch_1  | 	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:342) ~[elasticsearch-5.6.12.jar:5.6.12]
elasticsearch_1  | 	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:132) ~[elasticsearch-5.6.12.jar:5.6.12]
elasticsearch_1  | 	... 6 more
.....
...
..
```

What step I had missed? Why I cant start elastic search? please help...

**Comment by orangejulius** [comment]
This should be fixed by https://github.com/pelias/docker/pull/55, if anyone is still having trouble, let us know.
