### ISSUE TITLE
Self hosted planet build result deviation

### ISSUE THREAD

**Issue by MALKGITHUBER** [pelias/docker#331]
Hi Team,
First of all i want to appreaciate and Thanks all of the pelias Team efforts in making the pelias component such a great one,

Here i got some result deviation while building planet data
<img width="1440" alt="Screenshot 2023-11-30 at 5 49 42 PM" src="https://github.com/pelias/docker/assets/96979948/de966fd1-0d77-4a38-b3b8-ed551500939b">

pelias-dashboard build  

![newpeliasdashboard](https://github.com/pelias/docker/assets/96979948/5ee2242e-8f54-42c9-899c-74028429012b)

There is some deviation in 

1. doc store size and,
2.  address Layer according to the pelias-dashoard,

 ran the build multiple times, getting the same result 

is there anything am i missing!!

Thanks in advance

**Comment by missinglink** [comment]
Hi @MALKGITHUBER, the data available via the APIs provided by https://geocode.earth contain some additions which aren't available in the free data we provide.

Your installation contains 689.1 million addresses which should be more than sufficient for most workloads.

**Comment by missinglink** [comment]
> doc store size might not be problem right

lower is better

**Comment by MALKGITHUBER** [comment]
Hi missinglink , 
How much acceptance test success rate is good for self hosted planet build ?

Here is my result, is this good to go

Aggregate test results
Pass: 355
Improvements: 9
Expected Failures: 116
Placeholders: 0
Regressions: 356
Total tests: 836
Took 37688ms
Test success rate 57.42%

FATAL ERROR: 356 regression(s) detected.
