### ISSUE TITLE
ideaforge

### ISSUE THREAD

**Issue by Team-Cpptr** [pelias/docker#353]
**Describe the bug**

**Steps to Reproduce**

**Expected behavior**

**Environment (please complete the following information):**

**Pastebin/Screenshots**

**Additional context**

**Comment by missinglink** [comment]
Closing due to lack of context / possibly created in error from a fork.

**Comment by Team-Cpptr** [comment]
> Closing due to lack of context / possibly created in error from a fork.

Mistakenly hit the Enter button while writing the issue at the start.
