### ISSUE TITLE
Excluding Address Layer Warnings?

### ISSUE THREAD

**Issue by akifaktas** [pelias/docker#359]
`"warnings":["performance optimization: excluding 'address' layer"]`

Why does this error occur? For a local country, for example, Italy, Brazil, etc., I don't encounter such a problem, but when I set up the planet, I get this warning. While this warning appears, I usually don't get the responses I want, and it often returns an empty response.

**Comment by missinglink** [comment]
I guess you figured out the answer on your own, the address layer contains a the fast majority of records in the index, so I'd the parser fails to detect both a house number and street name in the input then we exclude the address layer, this has a significant positive effect on query performance.
