### ISSUE TITLE
Confused about prerequisites?

### ISSUE THREAD

**Issue by GuidoS** [pelias/docker#39]
Based on the read me there is a need for docker, but then there is also a need for macintosh brew libraries? How are these two things connected, I thought that docker would not need core utils? 

Can this be explained or can a clear step by step tutorial be put in here?

**Comment by orangejulius** [comment]
Hey @GuidoS,
You're right that the actual Pelias code running inside the Docker containers will not need brew. However, there's a not completely unsubstantial amount of logic built into the `pelias` script that helps provide an easy interface to running the correct Docker images.

The [generic build workflow](https://github.com/pelias/docker#generic-build-workflow) gives a good overview. My guess is without coreutils, things like `curl` won't behave the same on a Mac as they would on say, a Linux machine. And since that bit of helper tooling operates on the "real" machine, not in a Docker container, it's a prerequisite.

Let me know if you have any more questions.

**Comment by GuidoS** [comment]
Hi @orangejulius,

Thanks for the information. Following the directions I was able to get this running on my macintosh.

That said, this left me scratching my head a bit for a couple of reasons:

- It is really unclear to me what is Pelias, Pelias CLI, and Pelias Docker? Are they all the same thing?
- Where is Elastic Cache running?
- Can Pelias run on a windows machine? Can it run on a windows machine/ubuntu machine?
- Should it be clear that this "docker tool" documentation is for Mac OSX users, but it is possible to run this else where?

If you can help me out with this I will be sure to make a pull request to the documentation with my best attempt to explain this for me and others. 

Thanks,

guido

**Comment by GuidoS** [comment]
Here is a step by step with issues and resolutions for how I built the docker version of pelius (not sure that this name makes sense as I think all the versions use docker). Please **review and close this ticket** if this is an accepted version of setting this up.

# Vagrantfile

- needed to make the disk size 50gb, used the **vagrant-disksize** plugin
- needed to push a copy of the generic setup script to vm, provisioned file into machine
- needed to have access to docker service, so added vagrant user to the docker group

```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

## run in shell prior to running this vm
## vagrant plugin install vagrant-disksize

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.network "private_network", ip: "192.168.33.10"
  config.disksize.size = '50GB'
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "8192"
    vb.cpus = 2
  end

  config.vm.provision "file", source: "./setup_pelias.sh", destination: "setup_pelias.sh"
  config.vm.provision "file", source: "./setup_pelias_docker.sh", destination: "setup_pelias_docker.sh"

  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update
    sudo apt-get -y install build-essential libssl-dev docker docker-compose
    sudo usermod -a -G docker vagrant
    curl -sL https://deb.nodesource.com/setup_8.x | sudo bash
    sudo apt-get install -y nodejs
  SHELL
end
```
# setup_pelias_docker.sh (generic setup)

- ran into issues working in the root on fresh ubuntu install, updated all root folder mentions to $HOME
- ran into issue trying to create a sym link into /usr/local/bin, chmod 777 the directory before making link
- didn't want to wait for all the data to download, altered data to pull only wof

```sh
#!/bin/bash
## from https://github.com/pelias/docker
set -x

# create directories
mkdir $HOME/code $HOME/data

# set proper permissions. make sure the user matches your `DOCKER_USER` setting in `.env`
chown 1000:1000 $HOME/code $HOME/data

# clone repo
cd $HOME/code
git clone https://github.com/pelias/docker.git
cd docker

# install pelias script
sudo chmod 777 /usr/local/bin
ln -s "$(pwd)/pelias" /usr/local/bin/pelias

# cwd
cd projects/portland-metro

# configure environment
sed -i '/DATA_DIR/d' .env
echo 'DATA_DIR='$HOME'/data' >> .env

# run build
pelias compose pull
pelias elastic start
pelias elastic wait
pelias elastic create
pelias download wof
pelias prepare wof
pelias import wof
pelias compose up

# optionally run tests
pelias test run
```

**Comment by orangejulius** [comment]
Nice. That looks about right.

You can probably avoid the `chmod 777` by running the `ln` command on the following line with `sudo`.

Also, regarding downloads, `wof` takes the longest to download, so if you're downloading it, you might as well download everything. `wof` only includes administrative data (cities, counties, countries, etc) and it will be filtered for _just_ the Portland metro area, so with only `wof` data, you won't get a very interesting result

**Comment by GuidoS** [comment]
What data would you recommend if you wanted this to build quickly?

**Comment by orangejulius** [comment]
I recommend you use `pelias download all` and `pelias import all` for the portland metro area.

**Comment by GuidoS** [comment]
Ok, this sounds good

**Comment by orangejulius** [comment]
Yeah, the portland metro area is already pretty small, so there's not much to be gained by trying to trim it down further. We picked it specifically as a starter case because it has excellent data coverage and is quick to import :)

**Comment by SethuJangid** [comment]
npm ERR! code EACCES
npm ERR! syscall open
npm ERR! path /home/ayt/.npm/_cacache/tmp/c779434b
npm ERR! errno -13
npm ERR! 
npm ERR! Your cache folder contains root-owned files, due to a bug in
npm ERR! previous versions of npm which has since been addressed.
npm ERR! 
npm ERR! To permanently fix this problem, please run:
npm ERR!   sudo chown -R 1000:1000 "/home/ayt/.npm"

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ayt/.npm/_logs/2021-07-05T07_08_36_824Z-debug.log
