### ISSUE TITLE
"prepare all" breaks with an error in import.sh

### ISSUE THREAD

**Issue by maksimov** [pelias/docker#41]
Been following the steps but got stuck on `prepare all`. Willing to poke at it myself, but would appreciate any pointers as to where to start with this. 

OS: OSX 10.12.6

```pelias prepare all
converting /data/openstreetmap/portland_oregon.osm.pbf to /data/polylines/extract.0sv
Creating extract at /data/placeholder/wof.extract
Done!
import...
populate fts...
optimize...
close...
Done!
2018/11/07 12:25:35 found 0 refs for way 5286456
2018/11/07 12:25:36 found 0 refs for way 5298970
2018/11/07 12:25:36 found 0 refs for way 5324246
2018/11/07 12:25:36 found 0 refs for way 5327816
2018/11/07 12:25:37 found 0 refs for way 5405306
2018/11/07 12:25:37 found 0 refs for way 5405439
2018/11/07 12:25:37 found 0 refs for way 5405464
2018/11/07 12:25:39 found 0 refs for way 5856772
2018/11/07 12:25:39 found 0 refs for way 5857544
2018/11/07 12:25:39 found 0 refs for way 5857801
2018/11/07 12:25:39 found 0 refs for way 5861021
2018/11/07 12:25:39 found 0 refs for way 5862738
2018/11/07 12:25:39 found 0 refs for way 5862863
2018/11/07 12:25:39 found 0 refs for way 5865809
2018/11/07 12:25:39 found 0 refs for way 5869233
2018/11/07 12:25:40 found 0 refs for way 34445840
2018/11/07 12:25:41 found 0 refs for way 89783436
2018/11/07 12:25:42 found 0 refs for way 116187614
2018/11/07 12:25:42 found 0 refs for way 116211262
2018/11/07 12:25:44 found 0 refs for way 169287313
2018/11/07 12:25:45 found 0 refs for way 178881852
2018/11/07 12:25:46 found 0 refs for way 234502184
2018/11/07 12:25:48 found 0 refs for way 481849521
wrote polylines extract
-rw-r--r-- 1 pelias pelias 3.8M Nov  7 12:26 /data/polylines/extract.0sv
- importing polylines
/code/pelias/interpolation/script/import.sh: line 41:    21 Broken pipe             cat $POLYLINE_FILE
        22 Killed                  | node $DIR/../cmd/polyline.js $STREET_DB > $PROC_STDOUT 2> $PROC_STDERR
```

**Comment by orangejulius** [comment]
Hey @maksimov,
Thanks for trying things out. I _hope_ the cause of this is something straightforward like running out of RAM or disk. Can you let me know if either of those are the case?

**Comment by missinglink** [comment]
Also please ensure you're running the latest containers with `pelias compose pull`

**Comment by maksimov** [comment]
Hey @orangejulius, thanks for getting back to me! Yeah, when I started I may have had only about 5G free on the disk. I later tried doing the French example, which ran for four days while I was busy freeing up the space, I gave up after all and found `/tmp/pelias/france` taken 32G. I think it may have been caught in a retrying loop which it couldn't handle. I'll rerun Portland Metro now that I have 50G free.

Thanks @missinglink, I'm pretty sure they were latest since I did it more or less straight away after discovering pelias. Will update anyway before I run again.

**Comment by maksimov** [comment]
@orangejulius I just reran Portland Metro again with 50G disk space to spare and it failed at the same spot again:
```
- importing polylines
/code/pelias/interpolation/script/import.sh: line 41:    23 Broken pipe             cat $POLYLINE_FILE
        24 Killed                  | node $DIR/../cmd/polyline.js $STREET_DB > $PROC_STDOUT 2> $PROC_STDERR
```

**Comment by orangejulius** [comment]
What's your Docker memory limit set to? Here's an old screenshot of where to look. I'd suggest at least 8. Unfortunately the default is much lower.
![image](https://user-images.githubusercontent.com/111716/48428899-f850d800-e739-11e8-8fd9-1a05c12c6b51.png)

**Comment by maksimov** [comment]
@orangejulius 1 CPU and 1 Gb 😱

**Comment by orangejulius** [comment]
Okay well, that would do it

**Comment by maksimov** [comment]
Set the settings to yours and it completed in just about an hour. Thanks very much!
