### ISSUE TITLE
Tiger, Transit, etc. actions should do nothing when not configured

### ISSUE THREAD

**Issue by adefarge** [pelias/docker#5]
In the project for France (PR #4), we don't use transit.
However, when running `pelias import all`, the cli still tries to import the transit data.
This is not a big problem as it only print a error message and everything else still works fine.

Another bigger problem is when using `pelias download all` with no configuration for interpolation. The whole tiger dataset is downloaded. The work around is to download everything individually, but still, it would be nice to be able to do `download all`.

**Comment by orangejulius** [comment]
Agreed, we should be able to fix both fairly easily.

**Comment by orangejulius** [comment]
Both of these issues have now been fixed! hope it helps.
