### ISSUE TITLE
error network pelias_default is ambiguous

### ISSUE THREAD

**Issue by jeremy-rutman** [pelias/docker#51]
Hi. I am getting started w pelias and have hit something I dont know how to work with - 'network pelias_default is ambiguous' - 

```
root@jeremy-TECRA-Z40-C-pipl:/home/jeremy/pelias_docker/docker/projects/portland-metro# docker run hello-world
```
runs fine.  A first run of pelias compose pull downloaded a bunch of stuff, then:

```
root@jeremy-TECRA-Z40-C-pipl:/home/jeremy/pelias_docker/docker/projects/portland-metro# pelias compose pull
ERROR: 5 matches found based on name: network pelias_default is ambiguous
root@jeremy-TECRA-Z40-C-pipl:/home/jeremy/pelias_docker/docker/projects/portland-metro# pelias compose ps
ERROR: 5 matches found based on name: network pelias_default is ambiguous
root@jeremy-TECRA-Z40-C-pipl:/home/jeremy/pelias_docker/docker/projects/portland-metro# pelias test run 
ERROR: 5 matches found based on name: network pelias_default is ambiguous
root@jeremy-TECRA-Z40-C-pipl:/home/jeremy/pelias_docker/docker/projects/portland-metro# pelias system check
root@jeremy-TECRA-Z40-C-pipl:/home/jeremy/pelias_docker/docker/projects/portland-metro# pelias system env
...
USERNAME=root
SUDO_COMMAND=/bin/su
USER=root
PWD=/home/jeremy/pelias_docker/docker/projects/portland-metro
COMPOSE_PROJECT_NAME=pelias
HOME=/root
SUDO_USER=jeremy
DOCKER_USER=1000
SUDO_UID=1000
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
root@jeremy-TECRA-Z40-C-pipl:/home/jeremy/pelias_docker/docker/projects/portland-metro# pelias system update
Already up to date.
```

any help would be appreciated.
This is with Docker version 18.06.1-ce, build e68fc7a, Ubuntu 18.04.1 LTS

**Comment by jeremy-rutman** [comment]
this seemed to be a result of docker having been installed using 'snap' , reinstall by standard means seems to have solved the problem.

**Comment by orangejulius** [comment]
Hey @jeremy-rutman,
Thanks for all the reports. This one we've actually seen before, and it's caused by the weird fact that running `docker-compose up [container]` on several containers in the same network very rapidly (as our `pelias compose up` command does) will create duplicate networks.

We "cleverly" work around this by asking users to run `pelias elastic start` first (which only starts a single container, and thus resolves the race condition), but we knew that is kinda a hack on our part. I may push a branch in the near future to try to fix this, would you have a minute to test it out?

**Comment by jeremy-rutman** [comment]
yes no problem - iiuc this has nothing to do with snap and would just involve testing with 'vanilla' (aptitude-installed)  docker

**Comment by jeremy-rutman** [comment]
This still seems to happen with latest version: 
`jeremyr@aaa:/xxx/yyy/pelias/docker/projects/portland-metro$ pelias elastic start
ERROR: network pelias_default is ambiguous (6 matches found based on name)
`
same thing happens with `pelias compose pull`

**Comment by jeremy-rutman** [comment]
a workaround is `docker network rm $(docker network ls -q)`  which kills the extant networks and then `pelias elastic start`  . I blv the fix in https://github.com/pelias/docker/commit/41115a028be6398420c8a49d2ac2f23a5bb38f04 is only affecting compose-run , I will see if I can figure out how the shell is being used to run docker to fix it

**Comment by stefanocudini** [comment]
I noticed that this problem is still present ... in my opinion it can be defined as a bug because it is easily replicable
maybe you should add it in the documentation
