### ISSUE TITLE
elastic search not starting 

### ISSUE THREAD

**Issue by jeremy-rutman** [pelias/docker#53]
Following  `pelias compose pull` and `pelias elastic start` the `pelias elastic wait` is running into some problem - 

```
jeremy@jeremy:$ pelias elastic start
pelias_elasticsearch is up-to-date
jeremy@jeremy:$ pelias elastic wait
waiting for elasticsearch service to come up
.hist.ory|grep pelias.
...........................
Elasticsearch did not come up, check configuration

jeremy@jeremy:$ pelias elastic status
000
jeremy@jeremy:$ pelias test run 
{ Error: getaddrinfo ENOTFOUND api api:4000
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:57:26)
  errno: 'ENOTFOUND',
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'api',
...
```
and i am not sure what configuration I am supposed to be checking ; the data dir exists and is writable .
the elastic status of 000 is (I guess) indicating no elasticsearch .

the logs show 
```
elasticsearch_1  | [2018-11-26T14:33:11,234][INFO ][o.e.n.Node               ] [] initializing ...
elasticsearch_1  | [2018-11-26T14:33:11,263][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [] uncaught exception in thread [main]
elasticsearch_1  | org.elasticsearch.bootstrap.StartupException: java.lang.IllegalStateException: Failed to create node environment

...

java.nio.file.AccessDeniedException: /usr/share/elasticsearch/data/nodes    

```

**Comment by jeremy-rutman** [comment]
this was due to having my data dir be writable by world , apparently - when i used /tmp/pelias as data_dir i got the error above, moving to data under portland-metro works ...

```
jeremy@jeremy-TECRA-Z40-C-pipl:~/pelias_docker/docker/projects/portland-metro$ ls -l /tmp/pelias/
total 4
drwxrwxrwx 3 root root 4096 Nov 26  2018 portland-metro
jeremy@jeremy-TECRA-Z40-C-pipl:~/pelias_docker/docker/projects/portland-metro$ ls -l 
total 32
...
drwxrwxr-x 3 jeremy jeremy 4096 Nov 26 16:57 data

```

**Comment by orangejulius** [comment]
We've seen this one before too :). Hopefully, we can make the docker setup a bit more resilient to running as different users (official instructions are to run as a non-root users, but as many people can only run docker commands as root, that's not always possible).

Can you test out https://github.com/pelias/docker/pull/55 to see if it helps with your original situation? Thanks!
