### ISSUE TITLE
Incorrect path to pip service

### ISSUE THREAD

**Issue by dianashk** [pelias/docker#7]
Hey team, this new docker repo is great! Thanks for the awesome work.

Small issue with the sample projects and the pip service. In the sample projects, the path is set in the [config](https://github.com/pelias/docker/blob/master/projects/portland-metro/pelias.json#L28) which should correspond to whatever the service was named in the [`docker-compose.yml` file](https://github.com/pelias/docker/blob/master/projects/portland-metro/docker-compose.yml#L83).

Unfortunately it’s `pip` in the yml and `pip-service` in the config leading to errors in the API when coarse reverse is hit. Changing config to `pip` fixes the issue.

Cheers! 👋

**Comment by orangejulius** [comment]
Hey Diana. Nice catch. If you or @tigerlily-he want to submit a PR to fix this in all our `pelias.json` files in this repo (there are several now), we would definitely merge it! If not, we'll get to it soon.
