### ISSUE TITLE
pelias download all 

### ISSUE THREAD

**Issue by jeremy-rutman** [pelias/docker#77]
iiuc I need to create a /data directory on the root of my server to hold various downloads -  first of all I can't seem to change owner for anything right off the root /, and second putting downloads right at the root (and this dir not being configurable) seems poor form .  I  see several downloads attempting to put stuff at /data despite having specified DATA_DIR=/mnt/..../data, e.g. `curl -L -X GET -o /data/openaddresses/us-or-city_of_salem1Nu5o42N0ei0F.zip https://results.openaddresses.io/latest/run/us/or/city_of_salem.zip`

**Comment by jeremy-rutman** [comment]
maybe I am supposed to be editing docker-compose.yml and setting the ${DATA_DIR} there?  There are also ./blacklist entries, need I set those too? There abt 50 entries like $DATA_DIR and .blacklist which makes me wonder if this isnt supposed to be done automatically by the DATA_DIR entry in .env

**Comment by orangejulius** [comment]
Hi @jeremy-rutman,
That's correct, [setting `DATA_DIR` in .env](https://github.com/pelias/docker#variable-data_dir) is the recommended method. We use `/data` as a default, but it can be changed.

Note that _inside the docker containers, the data directory is _always_ mounted as `/data`, and you will see that in a lot of the output of many of the commands like the download you linked above. However, that doesn't mean there has to be a `/data` directory on your actual system.

**Comment by jeremy-rutman** [comment]
so it seems what I'm supposed to do here is edit pelias.json and change the data_dirs there - would it be possible to just have the data_dir in .env  propagate to set all those  ?

**Comment by orangejulius** [comment]
You shouldn't have to change the values in `pelias.json`. Those values are correct _inside_ the docker containers, where the DATA_DIR is always mounted as `/data`.

It looks like something else is happening, `curl` is having trouble connecting to the internet:
`Could not resolve host: results.openaddresses.io`

**Comment by jeremy-rutman** [comment]
yes, I'm seeing a lot of these EAI_AGAIN  errs, which afaict are timeouts , maybe the downloads are being attempted too quickly ?? 

```
 { Error: getaddrinfo EAI_AGAIN biketownpdx.socialbicycles.com biketownpdx.socialbicycles.com:80
    at doRequestWith (/code/pelias/transit/node_modules/sync-request/index.js:87:17)
    at doRequest (/code/pelias/transit/node_modules/sync-request/index.js:20:10)
    at downloadFile (/code/pelias/transit/lib/prep_data.js:82:20)
    at /code/pelias/transit/lib/prep_data.js:35:17
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/code/pelias/transit/lib/prep_data.js:25:21)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12) code: 'EAI_AGAIN' }
```

**Comment by jeremy-rutman** [comment]
I reset everything in pelias.json and docker-compose.yaml  to their original (/data) values and hit the above errs - in a hacky attempt to combat too-fast downloads I added a 'sleep 1 ' to the ends of the commands in https://github.com/pelias/docker/blob/master/cmd/download.sh , to no avail .   In case it helps, the full output from my `pelias download all` is:

> 
> deploy@dap-jupyter01:/mnt/open_street_map/docker/projects/portland-metro$ pelias elastic create
> 
> --------------
>  create index 
> --------------
> 
> [put mapping] 	 pelias { acknowledged: true,
>   shards_acknowledged: true,
>   index: 'pelias' } 
> 
> deploy@dap-jupyter01:/mnt/open_street_map/docker/projects/portland-metro$ pelias download all
> info: [openaddresses-download] Attempting to download selected data files: us/or/portland_metro.csv,us/or/city_of_salem.csv,us/or/marion_and_polk.csv,us/or/marion.csv,us/or/hood_river.csv,us/wa/city_of_richland.csv,us/wa/clark.csv
> info: [openaddresses-download] Downloading us/or/portland_metro.csv
> info: [openaddresses-download] Downloading us/or/city_of_salem.csv
> info: [openaddresses-download] Downloading us/or/marion_and_polk.csv
> info: [openaddresses-download] Downloading us/or/marion.csv
> info: [openaddresses-download] Downloading us/or/hood_river.csv
> info: [openstreetmap-download] Downloading sources: https://s3.amazonaws.com/metro-extracts.nextzen.org/portland_oregon.osm.pbf
> info: [csv-download] Attempting to download selected data files: https://raw.githubusercontent.com/pelias/csv-importer/master/data/example.csv
> info: [csv-download] Downloading https://raw.githubusercontent.com/pelias/csv-importer/master/data/example.csv to /data/csv/example.csv
> [whosonfirst-sqlite-download]	 https://dist.whosonfirst.org/sqlite/whosonfirst-data-latest.db.bz2
>                                                                                                    wget http://biketownpdx.socialbicycles.com/opendata/station_information.json to /data/transit/BIKETOWN-hubs.json
> Could not use "nc", falling back to slower node.js method for sync requests.
> error: [download] Failed to download data message=Command failed: curl -L -X GET -o /data/openaddresses/us-or-city_of_salem1wn21ouPsBBBV.zip https://results.openaddresses.io/latest/run/us/or/city_of_salem.zip
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
>   0     0    0     0    0     0      0      0 --:--:--  0:00:03 --:--:--     0curl: (6) Could not resolve host: results.openaddresses.io
> , stack=Error: Command failed: curl -L -X GET -o /data/openaddresses/us-or-city_of_salem1wn21ouPsBBBV.zip https://results.openaddresses.io/latest/run/us/or/city_of_salem.zip
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
>   0     0    0     0    0     0      0      0 --:--:--  0:00:03 --:--:--     0curl: (6) Could not resolve host: results.openaddresses.io
> 
>     at ChildProcess.exithandler (child_process.js:294:12)
>     at ChildProcess.emit (events.js:182:13)
>     at maybeClose (internal/child_process.js:962:16)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5), killed=false, code=6, signal=null, cmd=curl -L -X GET -o /data/openaddresses/us-or-city_of_salem1wn21ouPsBBBV.zip https://results.openaddresses.io/latest/run/us/or/city_of_salem.zip
> { Error: getaddrinfo EAI_AGAIN biketownpdx.socialbicycles.com biketownpdx.socialbicycles.com:80
>     at doRequestWith (/code/pelias/transit/node_modules/sync-request/index.js:87:17)
>     at doRequest (/code/pelias/transit/node_modules/sync-request/index.js:20:10)
>     at downloadFile (/code/pelias/transit/lib/prep_data.js:82:20)
>     at /code/pelias/transit/lib/prep_data.js:35:17
>     at Array.forEach (<anonymous>)
>     at Object.<anonymous> (/code/pelias/transit/lib/prep_data.js:25:21)
>     at Module._compile (internal/modules/cjs/loader.js:689:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
>     at Module.load (internal/modules/cjs/loader.js:599:32)
>     at tryModuleLoad (internal/modules/cjs/loader.js:538:12) code: 'EAI_AGAIN' }
> Had an issue obtaining new file /data/transit/BIKETOWN-hubs.json
> wget http://developer.trimet.org/schedule/gtfs.zip to /data/transit/TRIMET-stops.txt
> error: [openstreetmap-download] Failed to download data message=Command failed: cd /data/openstreetmap && { curl -L -X GET --silent --fail --remote-name https://s3.amazonaws.com/metro-extracts.nextzen.org/portland_oregon.osm.pbf; }
> , stack=Error: Command failed: cd /data/openstreetmap && { curl -L -X GET --silent --fail --remote-name https://s3.amazonaws.com/metro-extracts.nextzen.org/portland_oregon.osm.pbf; }
> 
>     at ChildProcess.exithandler (child_process.js:294:12)
>     at ChildProcess.emit (events.js:182:13)
>     at maybeClose (internal/child_process.js:962:16)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5), killed=false, code=6, signal=null, cmd=cd /data/openstreetmap && { curl -L -X GET --silent --fail --remote-name https://s3.amazonaws.com/metro-extracts.nextzen.org/portland_oregon.osm.pbf; }
> events.js:183
>       throw er; // Unhandled 'error' event
>       ^
> 
> Error: getaddrinfo EAI_AGAIN ftp2.census.gov:21
>     at Object._errnoException (util.js:992:11)
>     at errnoException (dns.js:55:15)
>     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)
> info: [csv-download] all done
> [status 000]	 https://dist.whosonfirst.org/sqlite/whosonfirst-data-latest.db.bz2
> 
>                                                                                    /code/pelias/whosonfirst/node_modules/better-sqlite3/lib/database.js:48
>                                                   	return new CPPDatabase(filename, filenameGiven, memory, readonly, fileMustExist);
>                                  	       ^
>                                                 SqliteError: unable to open database file
>                                                                                              at new Database (/code/pelias/whosonfirst/node_modules/better-sqlite3/lib/database.js:48:9)
>                                                                                     at findSubdivisions (/code/pelias/whosonfirst/utils/sqlite_extract_data.js:212:12)
>                                                                   at download (/code/pelias/whosonfirst/utils/download_data.js:19:26)
>                                  at /code/pelias/whosonfirst/node_modules/async/dist/async.js:3888:9
>                                                                                                         at /code/pelias/whosonfirst/node_modules/async/dist/async.js:473:16
>                                                                        at iterateeCallback (/code/pelias/whosonfirst/node_modules/async/dist/async.js:992:24)
>                                                          at /code/pelias/whosonfirst/node_modules/async/dist/async.js:969:16
>                         at /code/pelias/whosonfirst/node_modules/async/dist/async.js:3885:13
>                                                                                                 at ChildProcess.child.on.code (/code/pelias/whosonfirst/utils/sqlite_download.js:45:9)
>                                                                                   at ChildProcess.emit (events.js:182:13)
>                  { Error: getaddrinfo EAI_AGAIN developer.trimet.org developer.trimet.org:80
>     at doRequestWith (/code/pelias/transit/node_modules/sync-request/index.js:87:17)
>     at doRequest (/code/pelias/transit/node_modules/sync-request/index.js:20:10)
>     at downloadFile (/code/pelias/transit/lib/prep_data.js:73:20)
>     at /code/pelias/transit/lib/prep_data.js:35:17
>     at Array.forEach (<anonymous>)
>     at Object.<anonymous> (/code/pelias/transit/lib/prep_data.js:25:21)
>     at Module._compile (internal/modules/cjs/loader.js:689:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
>     at Module.load (internal/modules/cjs/loader.js:599:32)
>     at tryModuleLoad (internal/modules/cjs/loader.js:538:12) code: 'EAI_AGAIN' }
> Had an issue obtaining new file /data/transit/TRIMET-stops.txt
> wget http://www.c-tran.com/images/Google/GoogleTransitUpload.zip to /data/transit/C-TRAN-stops.txt
> { Error: getaddrinfo EAI_AGAIN www.c-tran.com www.c-tran.com:80
>     at doRequestWith (/code/pelias/transit/node_modules/sync-request/index.js:87:17)
>     at doRequest (/code/pelias/transit/node_modules/sync-request/index.js:20:10)
>     at downloadFile (/code/pelias/transit/lib/prep_data.js:73:20)
>     at /code/pelias/transit/lib/prep_data.js:35:17
>     at Array.forEach (<anonymous>)
>     at Object.<anonymous> (/code/pelias/transit/lib/prep_data.js:25:21)
>     at Module._compile (internal/modules/cjs/loader.js:689:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
>     at Module.load (internal/modules/cjs/loader.js:599:32)
>     at tryModuleLoad (internal/modules/cjs/loader.js:538:12) code: 'EAI_AGAIN' }
> Had an issue obtaining new file /data/transit/C-TRAN-stops.txt
> wget http://oregon-gtfs.com/gtfs_data/rideconnection-or-us/rideconnection-or-us.zip to /data/transit/RIDECONNECTION-stops.txt
> { Error: getaddrinfo EAI_AGAIN oregon-gtfs.com oregon-gtfs.com:80
>     at doRequestWith (/code/pelias/transit/node_modules/sync-request/index.js:87:17)
>     at doRequest (/code/pelias/transit/node_modules/sync-request/index.js:20:10)
>     at downloadFile (/code/pelias/transit/lib/prep_data.js:73:20)
>     at /code/pelias/transit/lib/prep_data.js:35:17
>     at Array.forEach (<anonymous>)
>     at Object.<anonymous> (/code/pelias/transit/lib/prep_data.js:25:21)
>     at Module._compile (internal/modules/cjs/loader.js:689:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
>     at Module.load (internal/modules/cjs/loader.js:599:32)
>     at tryModuleLoad (internal/modules/cjs/loader.js:538:12) code: 'EAI_AGAIN' }
> Had an issue obtaining new file /data/transit/RIDECONNECTION-stops.txt
> wget http://oregon-gtfs.com/gtfs_data/sandy-or-us/sandy-or-us.zip to /data/transit/SAM-stops.txt
> { Error: getaddrinfo EAI_AGAIN oregon-gtfs.com oregon-gtfs.com:80
>     at doRequestWith (/code/pelias/transit/node_modules/sync-request/index.js:87:17)
>     at doRequest (/code/pelias/transit/node_modules/sync-request/index.js:20:10)
>     at downloadFile (/code/pelias/transit/lib/prep_data.js:73:20)
>     at /code/pelias/transit/lib/prep_data.js:35:17
>     at Array.forEach (<anonymous>)
>     at Object.<anonymous> (/code/pelias/transit/lib/prep_data.js:25:21)
>     at Module._compile (internal/modules/cjs/loader.js:689:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
>     at Module.load (internal/modules/cjs/loader.js:599:32)
>     at tryModuleLoad (internal/modules/cjs/loader.js:538:12) code: 'EAI_AGAIN' }
> Had an issue obtaining new file /data/transit/SAM-stops.txt
> wget http://data.trilliumtransit.com/gtfs/wilsonville-or-us/wilsonville-or-us.zip to /data/transit/SMART-stops.txt
> { Error: getaddrinfo EAI_AGAIN data.trilliumtransit.com data.trilliumtransit.com:80
>     at doRequestWith (/code/pelias/transit/node_modules/sync-request/index.js:87:17)
>     at doRequest (/code/pelias/transit/node_modules/sync-request/index.js:20:10)
>     at downloadFile (/code/pelias/transit/lib/prep_data.js:73:20)
>     at /code/pelias/transit/lib/prep_data.js:35:17
>     at Array.forEach (<anonymous>)
>     at Object.<anonymous> (/code/pelias/transit/lib/prep_data.js:25:21)
>     at Module._compile (internal/modules/cjs/loader.js:689:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
>     at Module.load (internal/modules/cjs/loader.js:599:32)
>     at tryModuleLoad (internal/modules/cjs/loader.js:538:12) code: 'EAI_AGAIN' }
> Had an issue obtaining new file /data/transit/SMART-stops.txt
> wget http://oregon-gtfs.com/gtfs_data/swanisland-or-us/swanisland-or-us.zip to /data/transit/SWAN-stops.txt
> { Error: getaddrinfo EAI_AGAIN oregon-gtfs.com oregon-gtfs.com:80
>     at doRequestWith (/code/pelias/transit/node_modules/sync-request/index.js:87:17)
>     at doRequest (/code/pelias/transit/node_modules/sync-request/index.js:20:10)
>     at downloadFile (/code/pelias/transit/lib/prep_data.js:73:20)
>     at /code/pelias/transit/lib/prep_data.js:35:17
>     at Array.forEach (<anonymous>)
>     at Object.<anonymous> (/code/pelias/transit/lib/prep_data.js:25:21)
>     at Module._compile (internal/modules/cjs/loader.js:689:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
>     at Module.load (internal/modules/cjs/loader.js:599:32)
>     at tryModuleLoad (internal/modules/cjs/loader.js:538:12) code: 'EAI_AGAIN' }
> Had an issue obtaining new file /data/transit/SWAN-stops.txt
> 
>

**Comment by jeremy-rutman** [comment]
my versions :
```
Docker version 18.06.3-ce, build d7080c1
docker-compose version 1.23.2, build 1110ad01
Debian GNU/Linux 8.11 (jessie)
```
maybe the docker-ce vs. non-ce?

**Comment by jeremy-rutman** [comment]
reinstall of docker and pelias didnt help .  If I just download everything manually will this affect anything down the line?

**Comment by jeremy-rutman** [comment]
I tried running the wof download commands from the container and hit  a permission error: 

```

deploy@dap-jupyter01:/mnt/open_street_map/pelias_docker/docker/projects/portland-metro$ docker run -it pelias/whosonfirst /bin/bash
pelias@e3d6f1ff07c0:/code/pelias/whosonfirst$ more bin/download 
#!/bin/bash

exec node ./utils/download_data.js
pelias@e3d6f1ff07c0:/code/pelias/whosonfirst$ exec node ./utils/download_data.js 
/code/pelias/whosonfirst/node_modules/fs-extra/lib/mkdirs/mkdirs-sync.js:45
        throw err0
        ^

Error: EACCES: permission denied, mkdir '/mnt/pelias'
    at Object.mkdirSync (fs.js:753:3)
    at mkdirsSync (/code/pelias/whosonfirst/node_modules/fs-extra/lib/mkdirs/mkdirs-sync.js:31:9)
    at mkdirsSync (/code/pelias/whosonfirst/node_modules/fs-extra/lib/mkdirs/mkdirs-sync.js:36:14)
    at Object.mkdirsSync (/code/pelias/whosonfirst/node_modules/fs-extra/lib/mkdirs/mkdirs-sync.js:36:14)
    at Object.download (/code/pelias/whosonfirst/utils/download_data_all.js:15:6)
    at Object.<anonymous> (/code/pelias/whosonfirst/utils/download_data.js:65:34)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)

```

**Comment by jeremy-rutman** [comment]
Tried running the docker commands directly and get the same sqlite error:

```
deploy@dap-jupyter01:/mnt/open_street_map/pelias_docker/docker/projects/portland-metro$ docker network create pelias_default &>/dev/null || true
deploy@dap-jupyter01:/mnt/open_street_map/pelias_docker/docker/projects/portland-metro$ docker-compose run --rm 'whosonfirst' './bin/download';
[whosonfirst-sqlite-download]	 https://dist.whosonfirst.org/sqlite/whosonfirst-data-latest.db.bz2
[status 000]	 https://dist.whosonfirst.org/sqlite/whosonfirst-data-latest.db.bz2

/code/pelias/whosonfirst/node_modules/better-sqlite3/lib/database.js:48
	return new CPPDatabase(filename, filenameGiven, memory, readonly, fileMustExist);
	       ^
SqliteError: unable to open database file
    at new Database (/code/pelias/whosonfirst/node_modules/better-sqlite3/lib/database.js:48:9)
    at findSubdivisions (/code/pelias/whosonfirst/utils/sqlite_extract_data.js:212:12)
    at download (/code/pelias/whosonfirst/utils/download_data.js:19:26)
    at /code/pelias/whosonfirst/node_modules/async/dist/async.js:3888:9
    at /code/pelias/whosonfirst/node_modules/async/dist/async.js:473:16
    at iterateeCallback (/code/pelias/whosonfirst/node_modules/async/dist/async.js:992:24)
    at /code/pelias/whosonfirst/node_modules/async/dist/async.js:969:16
    at /code/pelias/whosonfirst/node_modules/async/dist/async.js:3885:13
    at ChildProcess.child.on.code (/code/pelias/whosonfirst/utils/sqlite_download.js:45:9)
    at ChildProcess.emit (events.js:182:13)

```

**Comment by missinglink** [comment]
Hi @jeremy-rutman 

Looking at the output you posted above, I noticed several DNS timeout errors:
- `Could not resolve host: results.openaddresses.io`
- `Error: getaddrinfo EAI_AGAIN ftp2.census.gov:21`
- `Error: getaddrinfo EAI_AGAIN developer.trimet.org developer.trimet.org:80`
- `Error: getaddrinfo EAI_AGAIN www.c-tran.com www.c-tran.com:80`
- `Error: getaddrinfo EAI_AGAIN oregon-gtfs.com oregon-gtfs.com:80`

It seems unlikely that all of those servers are down at the same time, are you possibly experiencing network issues?

**Comment by missinglink** [comment]
I'd suggest reverting the changes you have made, I'm struggling to follow all the comments in this thread but I can confirm that the instructions in the readme are correct and will result in a successful build on linux/OSX:

- https://github.com/pelias/docker/tree/master/projects/portland-metro
- https://github.com/pelias/docker#configure-environment

**Comment by jeremy-rutman** [comment]
my issues apparently stemmed from working behind a proxy - to fix , use this [https://elegantinfrastructure.com/docker/ultimate-guide-to-docker-http-proxy-configuration/](proxy config) namely add your proxies to /etc/systemd/system/docker.service.d/https-proxy.conf  and then run the docker commands with `--network host`, or more to the point in docker-compose.yml add network_mode:host , e.g. 

  whosonfirst:
    network_mode: host

**Comment by I1mran** [comment]
check your docker user environment variable.
`echo ${DOCKER_USER}`

set your docker user environment variable other then .env file.

`sudo service docker stop
export DOCKER_USER=1000
sudo service docker start`

**Comment by MALKARAJ** [comment]
> Sorry for all the jumping about. My issues apparently stemmed from working behind a proxy - to fix , follow this [proxy config](https://docs.docker.com/config/daemon/systemd/) ; namely, add your proxies as described to /etc/systemd/system/docker.service.d/http-proxy.conf (and/or https instead of http) . Then run docker commands with `--network host`, or more to the point in docker-compose.yml add `network_mode:host` lines, for the services needing net access, e.g.
> 
> ```
>   whosonfirst:
>     network_mode: host
>     ...
> ```

@jeremy-rutman 
 please help me with this setup. I am getting the same error as like yours

**Comment by jeremy-rutman** [comment]
So it looks like you should follow the link in the message you quote to set up a proxy configuration
