### ISSUE TITLE
`pelias elastic drop` hangs without -f

### ISSUE THREAD

**Issue by orangejulius** [pelias/docker#8]
The `drop_schema` script from pelias/schema supports either a `-f/--force-yes` flag to drop the schema, or if that flag is not a CLI param, it will ask the user to type yes to confirm the schema drop.

Because we run all containers with the `-T` flag, we cannot actually send interactive text to a docker container once it has started.

Thus, running `pelias elastic drop` prints text asking for user input to confirm the schema drop, but never receives it, causing it to appear to hang forever.

Some ideas to fix this:
- Modify our `pelias` binary to always pass the `-f` flag so the drop happens immediately
- enable TTY allocation for this (or all) containers
- Add support in pelias/schema to detect when a TTY is not allocated, and fail with a clear error

**Comment by orangejulius** [comment]
For some reason this doesn't seem to be a problem for me any more. I don't believe anything changed either in my setup or in this repo that could impact this, but I'll leave it open a few more days, and if no one else has experienced it, I think we can close this.

@missinglink can you confirm that `pelias elastic drop` works right for you?

**Comment by orangejulius** [comment]
Looking for confirmation from @missinglink or others that this is or isn't still an issue.

**Comment by orangejulius** [comment]
Haven't heard of this being a problem, and it works fine for me. Looks to be resolved! :tada:

**Comment by missinglink** [comment]
3 months late to the party here but I tested it and it works fine for me, with and without the `-f`
