### ISSUE TITLE
user and group in .env

### ISSUE THREAD

**Issue by woiza** [pelias/docker#96]
.env:
COMPOSE_PROJECT_NAME=pelias
DATA_DIR=/data/pelias-docker-compose/
DOCKER_USER=1003
ENABLE_GEONAMES=true

How can I specify the groupid of my docker user?

**Comment by orangejulius** [comment]
Hey woiza,

As mentioned in [the docs](https://github.com/pelias/docker#variable-docker_user), `DOCKER_USER` passes straight through to the `user` option in docker, so it supports all the same [options](https://github.com/pelias/docker#variable-docker_user):

```
user | user:group | uid | uid:gid | user:gid | uid:group
```
